### ISSUE TITLE
RFC: Simply makefile and add a moby test command

### ISSUE THREAD

**Issue by dave-tucker** [linuxkit/linuxkit#1539]
The Makefile would be a lot simpler if we could removed the test targets and error test macro.

See: https://github.com/docker/moby/pull/1536#issuecomment-292542576

It would be great to have a `moby test` tool that would:
- run the tests and check for errors
- run a suite of tests based on some configuration

as `moby run $platform` support expands, I'd like to see the default for each platform (Windows/Mac/Linux/FreeBSD etc...) support a unified set of flags and the same boot methods. So, for example, `moby run -efi test-efi.iso` would be able to be run on every platform.

This would allow smoke tests to be easily automated on all platforms without need for a Makefile target.

E.g
```
moby build test/test.yml && moby test
```

Test suites could use YAML for configuration. For example the `test/suites/default.yml` might look like:

```yaml
name: default
run: default
tests:
  default:
    parameters: test-bzImage test-initrd.img test-cmdline
    logs: test.log
  iso:
    parameters: -iso test.iso
    logs: test-iso.log
  efi:
    parameters: -efi test-efi.iso
    logs: test-efi.log
```

A similar approach could be take for cloud platforms like GCP.
e.g `test/suites/cloud.yml`
```yaml
name: cloud
run: explicit
tests:
  gcp:
    parameters: gcp test.img.tar.gz
    logs: test-gcp.log
```

This can easily be expanded to add test suites for security, compliance etc...

`moby test` would auto-discover all test suites in the `suites` directory and decide which ones to run based on each suites configuration and any command-line flags passed to it. I haven't really thought of anything complex here beyond:

1) Just run the default suite
2) Run only the `cloud` or `ltp` suites

This is just a brain dump of my current thinking on how this might look. Hoping to discuss further in the comments and work towards a design that could one day be implemented!
