### ISSUE TITLE
onboot logs not showing up anywhere

### ISSUE THREAD

**Issue by deitch** [linuxkit/linuxkit#1688]
**Description**

Output from `onboot` containers do not appear to have persistent logs or to console.

When running a linuxkit image, the `onboot` containers should have their output both persistent and to console. There does appear to be a plan for more advanced logging based on https://github.com/linuxkit/linuxkit/blob/d422c70ac6da78da3d32237735d86eb9001df384/projects/logging/README.md but in the meantime, the output is not in `/var/log` (where `services` logs are) or on console.

**Steps to reproduce the issue:**

Simplest way is to take the sample `linuxkit.yml` and add an `onboot` service that just echos:

```yml
  - name: swap
    image: "alpine:3.5"
    readonly: true
    command: ["/bin/echo","I AM HERE"]
```

Look for "I AM HERE" in the console, or even an indication that a particular container failed.
