### ISSUE TITLE
Add Volume Plugin declaration component under LinuxKit YAML file

### ISSUE THREAD

**Issue by ajeetraina** [linuxkit/linuxkit#1710]
**Description**

Currently LinuxKit YAML configuration file lack Volume plugin component. Including it as image/service under YAML file will surely help storage vendors to bring up  their volume plugin driver.

**Comment by justincormack** [comment]
I think to some extent this is a `moby` issue as the question is really about how plugins fit in the whole moby model, and also how they fit post containerd 1.0. 

We can probably do something interim here though...

**Comment by ajeetraina** [comment]
I tried building gcp.yml which includes docker service and it went fine. Picked up RexRay as an example and tried to see if RexRay Volume Plugin comes up well. But I found that though RexRay volume plugin got installed, it failed to get initialised as shown:

> Listing out the services:

```
/ # runc list
ID          PID         STATUS      BUNDLE                        CREATED                          OWNER
dhcpcd      992         running     /containers/services/dhcpcd   2017-04-26T08:48:54.874415491Z   root
docker      1008        running     /containers/services/docker   2017-04-26T08:48:54.954881495Z   root
nginx       1034        running     /containers/services/nginx    2017-04-26T08:48:54.962589142Z   root
ntpd        1046        running     /containers/services/ntpd     2017-04-26T08:48:54.984681108Z   root
rngd        1107        running     /containers/services/rngd     2017-04-26T08:48:55.069346641Z   root
sshd        1088        running     /containers/services/sshd     2017-04-26T08:48:55.052915757Z   root

```
> Enter into docker service:

```
/ # runc exec -t docker sh
/ #
```

> Installing RexRay Volume Plugin:

```
/ # docker plugin install --grant-all-permissions rexray/gcepd GCEPD_TAG=rexray 
latest: Pulling from rexray/gcepd
f22a36c09c84: Download complete 
Digest: sha256:726ad65d8de5f667f5f3bb8b905ab15984061a139d165925ff4b4086da24d36a
Status: Downloaded newer image for rexray/gcepd:latest
Installed plugin rexray/gcepd

```


> Verifying if Plugin is actually installed:

/```
 # docker plugin ls
ID                  NAME                  DESCRIPTION                        ENABLED
dd929d53612b        rexray/gcepd:latest   REX-Ray for GCE Persistent Disks   false
```

Looks good. Let me create volume now:

```
/ # docker volume ls
DRIVER              VOLUME NAME
local               178178e10e87d0143a4f81c40545af6d2e4fc6d7792f955e4ac39e7d37bfa87f
local               244cb8fbacd9336782dcaf2ef59a042fb60b6a57da0158558cc30437cb2c0129
local               905911dc71fd24591e755d348ef63a02fcfb4549e59b946fbd1c21cc3cfd7d6d
local               f1d60bd0008374567dc5dc95c59c2165ab19e00efc88cf613a93775bd6f51451
```

> Inspecting the RexRay Volume Plugin: 

```
/ # docker plugin inspect rexray/gcepd
[
    {
        "Config": {
            "Args": {
                "Description": "",
                "Name": "",
                "Settable": null,
                "Value": null
            },
            "Description": "REX-Ray for GCE Persistent Disks",
            "Documentation": "https://github.com/codedellemc/rexray/.docker/plugin/gcepd",
            "Entrypoint": [
                "/rexray.sh",
                "rexray",
                "start",
                "-f",
                "--nopid"
            ],
            "Env": [
                {
                    "Description": "",
                    "Name": "REXRAY_FSTYPE",
                    "Settable": [
                        "value"
                    ],
                    "Value": "ext4"
                },
                {
                    "Description": "",
                    "Name": "REXRAY_LOGLEVEL",
                    "Settable": [
                        "value"
                    ],
                    "Value": "warn"
                },
                {
                    "Description": "",
                    "Name": "REXRAY_PREEMPT",
                    "Settable": [
                        "value"
                    ],
                    "Value": "false"
                },
                {
                    "Description": "",
                    "Name": "GCEPD_DEFAULTDISKTYPE",
                    "Settable": [
                        "value"
                    ],
                    "Value": ""
                },
                {
                    "Description": "",
                    "Name": "GCEPD_TAG",
                    "Settable": [
                        "value"
                    ],
                    "Value": ""
                },
                {
                    "Description": "",
                    "Name": "GCEPD_ZONE",
                    "Settable": [
                        "value"
                    ],
                    "Value": ""
                }
            ],
            "Interface": {
                "Socket": "rexray.sock",
                "Types": [
                    "docker.volumedriver/1.0"
                ]
            },
            "Linux": {
                "AllowAllDevices": true,
                "Capabilities": [
                    "CAP_SYS_ADMIN"
                ],
                "Devices": null
            },
            "Mounts": [
                {
                    "Description": "",
                    "Destination": "/dev",
                    "Name": "",
                    "Options": [
                        "rbind"
                    ],
                    "Settable": null,
                    "Source": "/dev",
                    "Type": "bind"
                }
            ],
            "Network": {
                "Type": "host"
            },
            "PropagatedMount": "/var/lib/libstorage/volumes",
            "User": {},
            "WorkDir": "",
            "rootfs": {
                "diff_ids": [
                    "sha256:5a2bb249f2f91dfa0d546f0e818d5799fc40b60643b785d4e10b4758072c8dd1"
                ],
                "type": "layers"
            }
        },
        "Enabled": false,
        "Id": "dd929d53612b37a60ea47d26d5e1e7cfb3d7d392fdfeb00c530cdc5454b159a8",
        "Name": "rexray/gcepd:latest",
        "PluginReference": "docker.io/rexray/gcepd:latest",
        "Settings": {
            "Args": [],
            "Devices": [],
            "Env": [
                "REXRAY_FSTYPE=ext4",
                "REXRAY_LOGLEVEL=warn",
                "REXRAY_PREEMPT=false",
                "GCEPD_DEFAULTDISKTYPE=",
                "GCEPD_TAG=rexray",
                "GCEPD_ZONE="
            ],
            "Mounts": [
                {
                    "Description": "",
                    "Destination": "/dev",
                    "Name": "",
                    "Options": [
                        "rbind"
                    ],
                    "Settable": null,
                    "Source": "/dev",
                    "Type": "bind"
                }
            ]
        }
    }
]
```

```
# docker volume create -d rexray/gcepd --name store1 --opt=size=10
Error response from daemon: create store1: Error looking up volume plugin rexray/gcepd: plugin "rexray/gcepd" not found
```


> Tried enabling the volume plugin:

```
/ # docker plugin enable rexray/gcepd
rexray/gcepd
```

> Again, tried it running: 

```
/ # docker volume create -d rexray/gcepd --name store1 --opt=size=10
Error response from daemon: create store1: Error looking up volume plugin rexray/gcepd: plugin "rexray/gcepd" not found
/ # docker plugin ls
ID                  NAME                  DESCRIPTION                        ENABLED
dd929d53612b        rexray/gcepd:latest   REX-Ray for GCE Persistent Disks   false
```

The status still says "false". No Luck !

**Comment by justincormack** [comment]
Hmm, no that looks like some sort of setup issue with the Docker container perhaps. It might be better to open a new issue for that.

**Comment by ajeetraina** [comment]
@justincormack Tried adding unboot entry as shown below:

``
image: "linuxkit/kernel:4.9.x"
cmdline: "console=ttyS0 console=tty0 page_poison=1"
init:

linuxkit/init:63eed9ca7a09d2ce4c0c5e7238ac005fa44f564b
linuxkit/runc:b0fb122e10dbb7e4e45115177a61a3f8d68c19a9
linuxkit/containerd:18eaf72f3f4f9a9f29ca1951f66df701f873060b
linuxkit/ca-certificates:eabc5a6e59f05aa91529d80e9a595b85b046f935
onboot:
name: sysctl
image: "linuxkit/sysctl:1f5ec5d5e6f7a7a1b3d2ff9dd9e36fd6fb14756a"
net: host
pid: host
ipc: host
capabilities:
CAP_SYS_ADMIN
readonly: true
name: dhcpcd
image: "linuxkit/dhcpcd:48e249ebef6a521eed886b3bce032db69fbb4afa"
binds:
/var:/var
/tmp/etc:/etc
capabilities:
CAP_NET_ADMIN
CAP_NET_BIND_SERVICE
CAP_NET_RAW
net: host
command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
name: sysfs
image: linuxkit/sysfs:6c1d06f28ddd9681799d3950cddf044b930b221c
name: binfmt
image: "linuxkit/binfmt:8881283ac627be1542811bd25c85e7782aebc692"
binds:
/proc/sys/fs/binfmt_misc:/binfmt_misc
readonly: true
name: format
image: "linuxkit/format:53748000acf515549d398e6ae68545c26c0f3a2e"
binds:
/dev:/dev
capabilities:
CAP_SYS_ADMIN
CAP_MKNOD
name: metadata
image: "linuxkit/metadata:c5567e65e9125f0a4c4b8cb9d56a86377be62652"
binds:
/dev:/dev
/var:/var
/tmp/etc/resolv.conf:/etc/resolv.conf
net: host
capabilities:
CAP_SYS_ADMIN
name: mount
image: "linuxkit/mount:d2669e7c8ddda99fa0618a414d44261eba6e299a"
binds:
/dev:/dev
/var:/var:rshared,rbind
capabilities:
CAP_SYS_ADMIN
rootfsPropagation: shared
command: ["/mount.sh", "/var/lib/docker"]
name: plugins
image: "library/alpine:3.5"
binds:
/run:/run
capabilities:
CAP_SYS_ADMIN
command: ["mkdir", "-p", "/run/docker/plugins"]
services:

name: rngd
image: "linuxkit/rngd:c42fd499690b2cb6e4e6cb99e41dfafca1cf5b14"
capabilities:
CAP_SYS_ADMIN
oomScoreAdj: -800
readonly: true
name: sshd
image: "linuxkit/sshd:e108d208adf692c8a0954f602743e0eec445364e"
capabilities:
all
net: host
pid: host
binds:
/var/config/ssh/authorized_keys:/root/.ssh/authorized_keys
/tmp/etc/resolv.conf:/etc/resolv.conf
name: dhcpcd
image: "linuxkit/dhcpcd:57a8ef29d3a910645b2b24c124f9ce9ef53ce703"
binds:
/var:/var
/tmp/etc:/etc
capabilities:
CAP_NET_ADMIN
CAP_NET_BIND_SERVICE
CAP_NET_RAW
net: host
oomScoreAdj: -800
name: nginx
image: "nginx:alpine"
capabilities:
CAP_NET_BIND_SERVICE
CAP_CHOWN
CAP_SETUID
CAP_SETGID
CAP_DAC_OVERRIDE
net: host
name: ntpd
image: "linuxkit/openntpd:a570316d7fc49ca1daa29bd945499f4963d227af"
capabilities:
CAP_SYS_TIME
CAP_SYS_NICE
CAP_SYS_CHROOT
CAP_SETUID
CAP_SETGID
net: host
name: docker
image: "linuxkit/docker-ce:741bf21513328f674e0cdcaa55492b0b75974e08"
capabilities:
all
net: host
mounts:
type: cgroup
options: ["rw","nosuid","noexec","nodev","relatime"]
binds:
/var/lib/docker:/var/lib/docker
/lib/modules:/lib/modules
/run/docker/plugins:/run/docker/plugins
files:
- path: etc/docker/daemon.json
contents: '{"debug": true}'

trust:
image:
- linuxkit/kernel
outputs:

format: kernel+initrd
format: gcp-img
``

**Comment by ajeetraina** [comment]
Tested with the latest LInuxKit release:


docker.yml

```
kernel:
  image: "linuxkit/kernel:4.9.x"
  cmdline: "console=tty0 page_poison=1"
init:
  - linuxkit/init:1b8a7e394d2ec2f1fdb4d67645829d1b5bdca037
  - linuxkit/runc:3a4e6cbf15470f62501b019b55e1caac5ee7689f
  - linuxkit/containerd:deaf5bf838bf7f131c2287ecff3ed9835b0497e2
  - linuxkit/ca-certificates:75cf419fb58770884c3464eb687ec8dfc704169d
onboot:
  - name: sysctl
    image: "linuxkit/sysctl:3aa6bc663c2849ef239be7d941d3eaf3e6fcc018"
  - name: sysfs
    image: linuxkit/sysfs:1244c5a86dfa2318c4e304af68d37e12367e1b7f
  - name: binfmt
    image: "linuxkit/binfmt:8ac5535f57f0c6f5fe88317b9d22a7677093c765"
  - name: format
    image: "linuxkit/format:180cb2dc1de5e60373385080f8148abf10a3afac"
  - name: mount
    image: "linuxkit/mount:ff5338822f20375b8913f5a80f9ed4f6ea9a592b"
    command: ["/mount.sh", "/var/lib/docker"]
  - name: plugins
    image: "library/alpine:3.4"
    binds:
     - /run:/run
    capabilities:
     - all
    command: ["mkdir", "-p", "/run/docker/plugins"]
services:
  - name: rngd
    image: "linuxkit/rngd:1fa4de44c961bb5075647181891a3e7e7ba51c31"
  - name: dhcpcd
    image: "linuxkit/dhcpcd:7d2b8aaaf20c24ad7d11a5ea2ea5b4a80dc966f1"
  - name: ntpd
    image: "linuxkit/openntpd:45deeb05f736162d941c9bf494983f655ab80aa5"
  - name: docker
    image: "linuxkit/docker-ce:668d62da6e3da081a8f8aca7db3e2a98adf5da59"
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /var/lib/docker:/var/lib/docker
     - /lib/modules:/lib/modules
     - /run/docker:/run/docker
files:
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
  - {path: /run/docker/plugins,  directory: true}
trust:
  org:
    - linuxkit
```


Building LInuxKitOS:

```
Ajeets-MacBook-Air:~ ajeetraina$ sudo moby build -output=iso-bios ./docker.yml
Extract kernel image: linuxkit/kernel:4.9.x
Add init containers:
Process init image: linuxkit/init:1b8a7e394d2ec2f1fdb4d67645829d1b5bdca037
Process init image: linuxkit/runc:3a4e6cbf15470f62501b019b55e1caac5ee7689f
Process init image: linuxkit/containerd:deaf5bf838bf7f131c2287ecff3ed9835b0497e2
Process init image: linuxkit/ca-certificates:75cf419fb58770884c3464eb687ec8dfc704169d
Add onboot containers:
  Create OCI config for linuxkit/sysctl:3aa6bc663c2849ef239be7d941d3eaf3e6fcc018
  Create OCI config for linuxkit/sysfs:1244c5a86dfa2318c4e304af68d37e12367e1b7f
  Create OCI config for linuxkit/binfmt:8ac5535f57f0c6f5fe88317b9d22a7677093c765
  Create OCI config for linuxkit/format:180cb2dc1de5e60373385080f8148abf10a3afac
  Create OCI config for linuxkit/mount:ff5338822f20375b8913f5a80f9ed4f6ea9a592b
  Create OCI config for library/alpine:3.4
Add service containers:
  Create OCI config for linuxkit/rngd:1fa4de44c961bb5075647181891a3e7e7ba51c31
  Create OCI config for linuxkit/dhcpcd:7d2b8aaaf20c24ad7d11a5ea2ea5b4a80dc966f1
  Create OCI config for linuxkit/openntpd:45deeb05f736162d941c9bf494983f655ab80aa5
  Create OCI config for linuxkit/docker-ce:668d62da6e3da081a8f8aca7db3e2a98adf5da59
Add files:
  etc/docker/daemon.json
  /run/docker/plugins
Create outputs:
  docker.iso
Ajeets-MacBook-Air:~ ajeetraina$ sudo scp docker.iso /Users/ajeetraina/Desktop/
Password:
Ajeets-MacBook-Air:~ ajeetraina$ 
```

This time Docker service didn't come up while booting this LinuxKitOS.
