### ISSUE TITLE
how to show the shell prompt on a (VirtualBox VM) machine console?

### ISSUE THREAD

**Issue by rgl** [linuxkit/linuxkit#1825]
I'm trying to boot LinuxKit inside a VirtualBox VM at https://github.com/rgl/linuxkit-vagrant but for some reason it does show me a shell prompt. Maybe because I've modified the kernel command line to make it use the machine console? That is, I've removed the `console=ttyS0` from the kernel command line:

```yaml
kernel:
  image: "linuxkit/kernel:4.9.x"
  cmdline: "page_poison=1"
```

Any clue to what needs to be done to make it show the shell at the machine console?

BTW, is the following error harmless?

```
ERRO[000] get event from shim error="rpc error: code = 13 desc = transport is closing" module="containerd/runtime-linux"
```
