### ISSUE TITLE
External disk doc lack of samples for such usage

### ISSUE THREAD

**Issue by HackToday** [linuxkit/linuxkit#1904]
**Description**

**Steps to reproduce the issue:**
I tried to use the samples from  https://github.com/linuxkit/linuxkit/tree/master/examples 

disktest.yml here:

```
kernel:
  image: "linuxkit/kernel:4.9.x"
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:cbd7ae748f0a082516501a3e914fa0c924ee941e
  - linuxkit/runc:24dfe632ed3ff53a026ee3fac046fd544434e2d6
  - linuxkit/containerd:f1130450206d4f64f0ddc13d15bb68435aa1ff61
  - linuxkit/ca-certificates:4e9a83e890e6477dcd25029fc4f1ced61d0642f4
onboot:
  - name: sysctl
    image: "linuxkit/sysctl:225c52c2d6f04a040663bac84cabf81825027f64"
  - name: binfmt
    image: "linuxkit/binfmt:603e5f064b3e8a64088c0fcf7a80d2783541ee1d"
  - name: dhcpcd
    image: "linuxkit/dhcpcd:ae03169274d19fe8841314fa5a6fea3c61adbf4e"
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: format
    image: "linuxkit/format:d78093e943f9c88386e30c00353f9476d34fb551"
    binds:
     - /dev:/dev
    capabilities:
     - CAP_SYS_ADMIN
     - CAP_MKNOD
  - name: mount
    image: "linuxkit/mount:fc7164d7c4e1fe5d1da395c7f949fb332cffe752"
    binds:
     - /dev:/dev
     - /var:/var:rshared,rbind
    capabilities:
     - CAP_SYS_ADMIN
    rootfsPropagation: shared
    command: ["/mount.sh", "/var/external"]
services:
  - name: rngd
    image: "linuxkit/rngd:69f951ce2a3a9534dbbc7ba8119e1df4391f06c0"
  - name: sshd
    image: "linuxkit/sshd:1613253e5def414e0dfd261acd0e191eadb5fedf"
    capabilities:
     - all
    net: host
    pid: host
    binds:
     - /root/.ssh:/root/.ssh
     - /etc/resolv.conf:/etc/resolv.conf
trust:
  image:
    - linuxkit/kernel
    - linuxkit/rngd
files:
  - path: root/.ssh/authorized_keys
    contents: ' your key here'
outputs:
  - format: kernel+initrd

```
linuxkit run qemu -disk foo.img  -disk-size 1024 disktest

linuxkit version:
```
linuxkit version 0.0
commit: 905ded081e18305132a0ad76d427a2ab1068370e
```

QEMU version:

```
QEMU emulator version 2.9.0
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers
```

**Describe the results you received:**

the booted VM not in normal state. and such failing message

```
INFO[0001] loading grpc service plugin "runtime-grpc"...  module=containerd
INFO[0001] loading grpc service plugin "images-grpc"...  module=containerd
INFO[0001] starting GRPC API server...                   module=containerd
INFO[0001] starting metrics API...                       metrics=":13337" module=containerd
[   19.356952] random: fast init done
INFO[0001] containerd successfully booted in 0.456163s   module=containerd
2017/05/26 03:09:46 Cannot open /proc/sys/net/ipv4/neigh/default/gc_thresh1: open /proc/sys/net/ipv4/neigh/default/gc_thresh1: no such file or directory
 - 000-sysctl
[   20.746699] IPVS: Creating netns size=2104 id=2
[   20.746933] IPVS: ftp: loaded support on port[0] = 21
2017/05/26 03:09:48 ENOENT opening /binfmt_misc/register is it mounted?
 - 001-binfmt
[   22.649679] IPVS: Creating netns size=2104 id=3
[   22.649940] IPVS: ftp: loaded support on port[0] = 21
no valid interfaces found
```

And ip show nothing ip is allocated.  and keyboard seems not interactive. In one word. the booted VM is not in right state.

**Describe the results you expected:**

The doc or samples have good use cases how to write valid yaml to make external disk work

**Comment by HackToday** [comment]
@deitch

**Comment by rneugeba** [comment]
@HackToday I strongly suspect that you need to update your `moby` tool. Recent changes mean that significant chunks of the container config are now stashed in the image and no longer in the YAML file. The fact that you see:
```
2017/05/26 03:09:48 ENOENT opening /binfmt_misc/register is it mounted?
```
suggests that your version of the moby tool is not adding the config from the image to the container config.

Could you try updating?

**Comment by HackToday** [comment]
Hi  @rneugeba , my moby version below:

# moby version
moby version 0.0
commit: 5eff65a6882f913e547889124e53b868e6a59043


Before I opened the issue, I git pull the latest repo, and make build those tools.

Is the version old ?

**Comment by rneugeba** [comment]
Unless you are pretty much on the latest version, you need to do a `make clean && make && make install`. The latest version is:
```
% moby version
moby version 0.0
commit: a81a48629be75b902063b4d83799b03972b9d7c7
```

**Comment by HackToday** [comment]
hi  @rneugeba ,  Thanks

I would pull latest version.

I noticed the example in yml files. For examples:

sshd or other 

 16   - name: format           
 17     image: "linuxkit/format:55afe08816c2a4d8dbae3ee51ef53e0bee422d66"
 18   - name: mount            
 19     image: "linuxkit/mount:15e20f27abe69d276f796e4026531833ec5ff345"
 20     command: ["/mount.sh", "/var/lib/docker"]


It was much different from previous version.  

No capabilities specified anymore 
(like  -    capabilities:		
 -     - CAP_SYS_ADMIN		
 -     - CAP_MKNOD)

Seems they are moved to each Dockerfile LABEL field.  Is it ?


If that case, just want to check what's the result would for the following ?  

in sshd.yml, I also specify:

```
  - name: sshd
    image: "linuxkit/sshd:ddce15b9fbde068941e31294acdcd22befa4fc20"
    binds:
     - /var/external:/var/external
```

It seems those binds here would override the default DOCKER LABEL (/root/.ssh:/root/.ssh", "/etc/resolv.conf:/etc/resolv.conf)


So where do we usually  set binds,  in DOCKERFILE or  in yml file ?
