### ISSUE TITLE
pxe boot kernel and initrd but no dhcp lease

### ISSUE THREAD

**Issue by nrocco** [linuxkit/linuxkit#1962]
**Description**

I use the `moby` tool to generate a minimal operating system with sshd (based on the examples given in this repository).

I place the generated `kernel` and `initrd.img` on a publicly accessible http server along with a `ipxe` configuration for bootstrapping a bare metal server (HP).

After power cycling the machine I can see pxe picking up the dhcp lease, reading the ipxe instructions, downloading both `kernel` and `initrd.img` and booting succesfully.

When the `initrd.img` is loaded I can see various messages being outputted to the console regarding `link not ready`. Booting the `initrd` takes roughly 2 minutes before dhcp times out and `runc` and `containerd` start.

**Steps to reproduce the issue:**

Create a `yaml` file `test.yml` with the following contents:

```
kernel:
  image: "linuxkit/kernel:4.9.x"
  cmdline: "page_poison=1 ip=dhcp nomodeset ro serial"

init:
  - linuxkit/init:1b8a7e394d2ec2f1fdb4d67645829d1b5bdca037
  - linuxkit/runc:3a4e6cbf15470f62501b019b55e1caac5ee7689f
  - linuxkit/containerd:deaf5bf838bf7f131c2287ecff3ed9835b0497e2
  - linuxkit/ca-certificates:75cf419fb58770884c3464eb687ec8dfc704169d

onboot:
  - name: sysctl
    image: "linuxkit/sysctl:3aa6bc663c2849ef239be7d941d3eaf3e6fcc018"

services:
  - name: rngd
    image: "linuxkit/rngd:1fa4de44c961bb5075647181891a3e7e7ba51c31"
  - name: dhcpcd
    image: "linuxkit/dhcpcd:7d2b8aaaf20c24ad7d11a5ea2ea5b4a80dc966f1"
  - name: sshd
    image: "linuxkit/sshd:abc1f5e096982ebc3fb61c506aed3ac9c2ae4d55"

files:
  - path: root/.ssh/authorized_keys
    contents: "ssh-rsa ....."

trust:
  org:
    - linuxkit
```

Then generate the kernel and initrd files:

```
moby build test.yml
```

Then create the following ipxe file `test.ipxe`:

```
#!ipxe
dhcp
set base http://ip.addr.of.your.http.server
kernel ${base}/test-kernel initrd=test-initrd.img page_poison=1 ip=dhcp nomodeset ro serial
initrd ${base}/test-initrd.img
boot
```

Finally copy the `test.ipxe`, `test-kernel and`test-initrd.img` to the webroot of `http://ip.addr.of.your.http.server`, create a dhcp lease pointing the boot file to `http://ip.addr.of.your.http.server/text.ipxe`

**Describe the results you received:**

After booting the generated operating system the machine does not have internet connectivity and the `sshd` service is not reachable.

**Describe the results you expected:**

I was expecting the machine to have received a dhcp lease for eth0 so I would be able to ssh in to the `sshd` service.

**Additional information you deem important (e.g. issue happens only occasionally):**

I notice in the console logs references to an interface `bond0` (see screenshot). I am not sure if this is related but it seems odd to me. Even though my server has two NICs I am sure that my bare metal server is only connected to the switch via one NIC.

<img width="673" alt="screen shot 2017-06-04 at 23 20 54" src="https://cloud.githubusercontent.com/assets/694012/26765695/98f0c566-4981-11e7-928f-e62313772f00.png">

I have tried to investigate any software component of `linuxkit` to see where this bonding configuration is coming from and how to configure it otherwise.
