### ISSUE TITLE
RFC: Mount partition with linuxkit/mount by label

### ISSUE THREAD

**Issue by pwFoo** [linuxkit/linuxkit#2123]
Would be nice to mount partitions (optional) by label instead of the first partition of type linux. 
mount.sh should handle a second (optional) ARG with the partition label which should be mounted

**Comment by justincormack** [comment]
`mount` definitely needs a bunch of options. Specifying the device as well should be supported! Most of the situations we have used the disks are likely blank so they don't have labels but I can see that there will be use cases for labels.

**Comment by ijc** [comment]
Possibly `format` should gain a similar set of options, including the ability to specify a label to apply to the fs it makes.

**Comment by pwFoo** [comment]
I modified the mount.sh script and built my own image, but the mount fails. I try to mount a partition by label to the mountpoint /var/lib/docker which is used by the docker service (yml based on docker.yml.

I try to prepare the /var/lib/docker directory (create, mount partition) used by the docker service.

caps / binds of linuxkit/mount should be fine. mount.sh likes like that (haven't the file here):
```
mkdir -p /var/lib/docker   # should be shared because of /var:/var
mount $PART $MOUNTPOINT   # = mount LABEL=mylabel /var/lib/docker (LABEL=mylabel == /dev/sda3)
```
I see the script output during boot (onboot section), but mount failed because of missing file / directory /var/lib/docker... ?!

System boots up fine with running docker with /var/lib/docker tmpfs.

Tested the docker file config:
```
LABEL org.mobyproject.config='{"binds": ["/dev:/dev", "/var:/var:rshared,rbind"], "capabilities": ["CAP_SYS_ADMIN"], "rootfsPropagation": "shared", "net": "new", "ipc": "new"}'
```
Also tested with options inside of the YML file.

Next / Later I'll try to add some more output / debugging information like `ls` commands and more to see why it fails...

**Comment by justincormack** [comment]
Can you include enough of the yaml file to reproduce.


On 2 Jul 2017 1:06 pm, "pwFoo" <notifications@github.com> wrote:

I modified the mount.sh script and built my own image, but the mount fails.
I try to mount a partition by label to the mountpoint /var/lib/docker which
is used by the docker service (yml based on docker.yml.

I try to prepare the /var/lib/docker directory (create, mount partition)
used by the docker service.

caps / binds of linuxkit/mount should be fine. mount.sh likes like that
(haven't the file here):

mkdir -p /var/lib/docker   # should be shared because of /var:/var
mount $PART $MOUNTPOINT   # = mount LABEL=mylabel /var/lib/docker
(LABEL=mylabel == /dev/sda3)

I see the script output during boot (onboot section), but mount failed
because of missing file / directory /var/lib/docker... ?!

System boots up fine with running docker with /var/lib/docker tmpfs.

Tested the docker file config:

LABEL org.mobyproject.config='{"binds": ["/dev:/dev",
"/var:/var:rshared,rbind"], "capabilities": ["CAP_SYS_ADMIN"],
"rootfsPropagation": "shared", "net": "new", "ipc": "new"}'

Also tested with options inside of the YML file.

Next / Later I'll try to add some more output / debugging information like
ls commands and more to see why it fails...

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/linuxkit/linuxkit/issues/2123#issuecomment-312487952>,
or mute the thread

**Comment by pwFoo** [comment]
YML file (based on docker.yml example):
```
kernel:
  image: "dengleros/kernel:4.11.x@sha256:49821298dc18b3386cf607626c54dec9de9d6a8279718903d3d0157a2d77cf59"
  cmdline: "console=ttyS0 console=tty0 page_poison=1"
init:
  - linuxkit/init:36c56f0664d49c5a6adc1120d1bf5ba6ac30b389
  - linuxkit/runc:291131ec026430371e7c36165c3f43734fbc2541
  - linuxkit/containerd:1e3e8f207421de8deac8cedc26a138d6b1661a0d
  - linuxkit/ca-certificates:46b59484919bfa9af700e54e042048cb06261de4
onboot:
  - name: modprobe
    image: "dengleros/modprobe@sha256:a3bdb974d8b622cfd832a952ec6dd4833d35dc4c2249a9a75604d9127c8108c7"
    binds:
     - /dev:/dev
     - /lib/modules:/lib/modules
     - /lib/firmware:/lib/firmware
    rootfsPropagation: shared
    capabilities:
     - CAP_SYS_MODULE
    command: [ "/modprobe.sh", "fbcon", "sd_mod" ]
  - name: sysctl
    image: "linuxkit/sysctl:3aa6bc663c2849ef239be7d941d3eaf3e6fcc018"
  - name: sysfs
    image: linuxkit/sysfs:b4091d81261f4582ff899a8510110fc4f2be2b49
  - name: binfmt
    image: "linuxkit/binfmt:24e2b996f7d6ad20bfa9c9f1564a3c6172db47ce"
  - name: format
    image: "linuxkit/format:ba085fdcac31c383acee3b4b91d78eb7095e5ac3"
  - name: mount
    image: "dengleros/mount@sha256:55c18f2efd60ac1da2cc9a46d051b8c30ab31a663769c65dd7ada883538182f8"
    binds:      
     - /dev:/dev
     - /lib/modules:/lib/modules
     - /lib/firmware:/lib/firmware
     - /var:/var:rshared,rbind
    rootfsPropagation: shared
    capabilities:
     - CAP_SYS_ADMIN
    command: ["/mount.sh", "/var/lib/docker", "LABEL=dengleros" ]
services:
  - name: getty
    image: "linuxkit/getty:6cbeee0392b0670053ce2bf05a5a0d67ec2bce05"
    env:
     - INSECURE=true
  - name: rngd
    image: "linuxkit/rngd:b50b22dd574c5377708977af769f053009fff6d5"
  - name: dhcpcd
    image: "linuxkit/dhcpcd:6c1ca76dbf808d5c27d10cbf22a8d4399be5c8ae"
  - name: ntpd
    image: "linuxkit/openntpd:a4c642d52e985922fcd97db52e471db123cc6841"
  - name: docker
    image: "linuxkit/docker-ce:9e125aa533108731d11f6d7ec17aba6ded0cb4eb"
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /var/lib/docker:/var/lib/docker
     - /lib/modules:/lib/modules
     - /lib/firmware:/lib/firmware
     - /dev:/dev
     - /var/run:/var/run:rshared,rbind
  - name: gui
    image: "dengleros/gui@sha256:160a90d28271eea6a1db70442f882c9c605910b8b2e2d89d392a4e529dc2b9c0"
    binds:
     - /var/run:/var/run:rshared,rbind
files:
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
trust:
  org:
    - linuxkit
```
docker service starts with tmpfs instead of the partition. 

Problem seems to be the mount onboot container. mount failed. It looks like the mountpoint is missing even though it's created by `mkdir -p ...`. mount is copied from the linuxkit pkg mount with modified mount.sh.

I think it's should be a caps problem, but it doesn't work with the included label (dockerfile) or configs within the YML.
