### ISSUE TITLE
How to load a additional kernel module during init?

### ISSUE THREAD

**Issue by pwFoo** [linuxkit/linuxkit#2128]
I have a special use case and need to load a additional kernel module manually.
What is the simplest way to manually load a kernel module during boot / init without modify the core packages of linuxkit (pkg init)?

**Comment by justincormack** [comment]
you can use an `onboot` package that just does `insmod` if you have built a module that is compatible with the kernel. Or you can add an additional `init` package with the module and a script that inserts it in `/etc/init.d/` and it will be called by `init`.

**Comment by pwFoo** [comment]
Tried to add as an onboot container:
```
onboot:
  - name: modprobe
    image: "dengleros/modprobe@sha256:a7b9afc134811141819bf9dcc7330d727d089a3c9f1c855eaff84e52ef14f1d4"
    command: ["fbcon"]
[...]
```

All modules inside of command will be loaded by modprobe. I use a custom kernel image with have additional modules. Before I loaded it inside a service without problems, but I'd try to separate different code like custom modprobe calls as onboot.
