### ISSUE TITLE
Unable to use terraform-provider-vsphere to specify network information for open-vm-tools container

### ISSUE THREAD

**Issue by stealthybox** [linuxkit/linuxkit#2243]
cc @thebsdbox @justincormack @rn 

**Description**
I'm successfully importing and booting LinuxKit vmdk's in vSphere with Terraform.
My environment does not have DHCP.
I would like to leverage vSphere and open-vm-tools to setup the vm's networking.

I've built several linuxkit images with a `vmtoolsd` container from the `linuxkit/open-vm-tools` image with varying capabilities. (none / all / CAP_NET_ADMIN + CAP_SYS_RAWIO)

I am able to remote-console into the vm in order to setup the NIC, Routes, and DNS.
When I manually configure the network from `getty`, I am able to ssh into the vm.

I have not been able to get vSphere to instruct vmtools to configure these automatically based off of the Terraform definition using a LinuxKit image, but this network configuration works to auto-provision our RHEL machines.

**Steps to reproduce the issue:**

Given the following linuxkit yaml adapted from the sshd example: `examples/vcenter.yml`:
```yaml
kernel:
  image: linuxkit/kernel:4.9.36
  cmdline: "console=tty0 console=ttyS0"
init:
  - linuxkit/init:059b2bb4b6efa5c58cf53fed4d0ea863521959fc
  - linuxkit/runc:4a35484aa6f90a1f06cdf1fb36f7056926a084b9
  - linuxkit/containerd:b6ffbb669248e3369081a6c4427026aa968a2385
  - linuxkit/ca-certificates:67acf038c44bb191ebb704ec7bb39a1524052cdf
onboot:
  - name: sysctl
    image: linuxkit/sysctl:d1a43c7c91e92374766f962dc8534cf9508756b0
services:
  - name: vmtoolsd
    image: linuxkit/open-vm-tools:1a7566742748bec0c1e0171705b77ef5ac947bba
    capabilities: ["all"]
  - name: getty
    image: linuxkit/getty:0bd92d5f906491c20e4177c57f965338fe5a8c5f
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:1516d5d70683a5d925fe475eb1b6164a2f67ac3b
  - name: sshd
    image: linuxkit/sshd:89b2e91d7d1bf2f40220be0e3ed586e74746cceb
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
trust:
  org:
    - linuxkit
```
Build the image into a desktop vmdk and import the vmdk into vSphere:
```bash
bin/moby build -output vmdk -output iso-bios examples/vcenter.yml
govc import.vmdk -dc '*Ph*' -ds '*2N07*' -pool '*2N07*/Resources/test_low' vcenter.vmdk linuxkit
```
Then `terraform apply` the following file:
```terraform
# Configure the VMware vSphere Provider
provider "vsphere" {
  user           = "${var.vsphere["user"]}"
  password       = "${var.vsphere["password"]}"
  vsphere_server = "${var.vsphere["server"]}"
  allow_unverified_ssl = true
}

# Create a deployment folder
resource "vsphere_folder" "deployment" {
  path       = "LinuxKit_Deployment"
  datacenter = "Phoenix"
}

# Create your vm's
resource "vsphere_virtual_machine" "app" {
  count  = 1
  vcpu   = 2
  memory = 4096

  name   = "linuxkit${count.index}"
  domain = "company.com"
  network_interface {
    label              = "10.55.0.0_23" # (p0_dvs_compute)
    ipv4_address       = "10.55.1.${count.index+5}"
    ipv4_gateway       = "10.55.1.254"
    ipv4_prefix_length = "23"
  }
  dns_servers   = [ "147.22.116.240" ]
  dns_suffixes  = [ "company.com" ]
  
  folder        = "${vsphere_folder.deployment.path}"
  datacenter    = "Phoenix"
  cluster       = "2N07"
  resource_pool = "2N07/Resources/production_medium"

  disk {
    datastore = "2N07_VSAN_H01"
    vmdk      = "/linuxkit/vcenter.vmdk"
    bootable  = true
  }
}
```
VMWare Remote Console into the vm should drop you into `getty`.

**Describe the results you received:**
- Terraform deploys the vm
- vSphere reports vmtools are installed
- open-vm-tools is running in ctr
- open-vm-tools does not log any errors in `ctr attach`
- :heavy_multiplication_x: NIC, Routes, and DNS are not configured

I played with different capabilities.
No capabiliites seemed necessary for vmTools to be reported as installed in the vSphere API.

Adding `CAP_NET_ADMIN` lets these commands work in the open-vm-tools namespace.
(get a tty: `ctr attach -t --exec-id 0 vmtoolsd ash`):
- `ifconfig eth0 <ip> netmask <nm>`
- `ip route add default via <gw>`

How I verified tools were registering with the vSphere API:
```
govc vm.info '/*P*/vm/*Kit*/*'
Name:           linuxkit0
  Path:         /Phoenix/vm/LinuxKit_Deployment/linuxkit0
  UUID:         423a2e73-dee4-7451-e82c-2d251ada5325
  Guest name:   Other Linux (64-bit)
  Memory:       4096MB
  CPU:          2 vCPU(s)
  Power state:  poweredOn
  Boot time:    2017-07-18 20:15:37.458018 +0000 UTC
  IP address:   
  Host:         host0070.company.com

govc vm.info -json '/*P*/vm/*Kit*/*'|jq .|grep -i tool
        "UnmountToolsInstaller",
        "UpgradeTools_Task",
        "UpgradeToolsFromImage_Task",
        "ToolsAutoUpdateSupported": false,
        "ToolsSyncTimeSupported": true,
        "Tools": {
          "ToolsVersion": 2147483647,
          "ToolsInstallType": "",
          "ToolsUpgradePolicy": "manual",
            "Key": "vmware.tools.internalversion",
            "Key": "vmware.tools.requiredversion",
        "ToolsInstallerMounted": false,
        "ToolsStatus": "toolsOk",
        "ToolsVersionStatus": "guestToolsUnmanaged",
        "ToolsVersionStatus2": "guestToolsUnmanaged",
        "ToolsRunningStatus": "guestToolsRunning",
        "ToolsVersion": "2147483647",
        "ToolsInstallType": "",
          "ToolsInstallerMounted": false,
          "ToolsStatus": "toolsOk",
          "ToolsVersionStatus": "guestToolsUnmanaged",
          "ToolsVersionStatus2": "guestToolsUnmanaged",
          "ToolsRunningStatus": "guestToolsRunning",
```

**Describe the results you expected:**
- vSphere reports vmtools are installed
- open-vm-tools configures the NIC with the IP and CIDR
- open-vm-tools configures the Routing Tables
- open-vm-tools configures DNS

**Additional information you deem important (e.g. issue happens only occasionally):**
Environment:
- vSphere 6.0
- Linuxkit Commit: 6295d0e425144d552ce52a4efa2a54ccc646e737
- govc version: 0.15.0
- terraform version: v0.9.5

References:
- [linuxkit hypervisor tools docs](https://github.com/linuxkit/linuxkit/blob/master/docs/virtual-os-tools.md)
- [linuxkit open-vm-tools Dockerfile](https://github.com/linuxkit/linuxkit/blob/master/pkg/open-vm-tools/Dockerfile)
- [vmware open-vm-tools GitHub](https://github.com/vmware/open-vm-tools)
- [vmware blogpost on containerising open-vm-tools for Atomic](https://developers.redhat.com/blog/2017/03/23/containerizing-open-vm-tools-part-1-the-dockerfile-and-constructing-a-systemd-unit-file/)

open-vm-tools only logs errors by default.

we may be able to get more visibility into what's happenning by enabling debug logging by adding a config to the vmtoolsd container.
[source1](http://www.running-system.com/how-to-enable-vmware-tools-debug-logging/) | [source2](https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1007873)
