### ISSUE TITLE
modprobe onboot pkg 

### ISSUE THREAD

**Issue by pwFoo** [linuxkit/linuxkit#2367]
I use a custom modprobe onboot container to load additional kernel modules. Maybe it could be useful?
I don't know about how to do a correct PR or tests, so I post the pkg content here.
 

Adding a modprobe onboot pkg to load additional kernel modules by kernel cmdline or docker cmd.

Usage onboot package:
```
onboot:
  - name: modprobe
    image: "dengleros/modprobe@sha256:11ba83c31f46e02da3b41825a0ba91b6b858003cc114d9c1ee700de26ee27d35"
    command: [ "/modprobe.sh", "fbcon", "sd_mod", "ext3", "ext4" ]
```

Usage kernel parameters:
```
linux /boot/linuxkit-kernel console=tty0 module=fbcon module=sd_mod ...
```

dockerfile 
```
FROM    alpine:latest

COPY    files/ /

CMD     [ "/modprobe.sh", "fbcon", "sd_mod", "ext3", "ext4" ]

LABEL org.mobyproject.config='{"binds": ["/dev:/dev", "/lib/modules:/lib/modules", "/lib/firmware:/lib/firmware" ], "capabilities": ["CAP_SYS_MODULE"], "rootfsPropagation": "shared", "net": "new", "ipc": "new"}'
```

files/modprobe.sh
```
#!/bin/sh

set -x


MODULES="$@"


# detect load modules from cmdline
for opt in $(cat /proc/cmdline); do
    case "$opt" in
        module=*)
            MODULES="$MODULES ${opt#module=}"
    esac
done


# load modules
for MODULE in $MODULES; do
    modprobe $MODULE
done
```
