### ISSUE TITLE
cannot bind to new targets with ro rootfs.

### ISSUE THREAD

**Issue by ijc** [linuxkit/linuxkit#2503]
This is similar to https://github.com/kubernetes-incubator/cri-containerd/issues/220 but here affects e.g. the sysctl container with a custom sysctl file. Previously it was possible to do:
```
onboot:
  - name: sysctl
    image: linuxkit/sysctl:154913b72c6f1f33eb408609fca9963628e8c051
    binds:
     - /etc/sysctl.d/01-ip_forward.conf:/etc/sysctl.d/01-ip_forward.conf
[...]
files:
  - path: /etc/sysctl.d/01-ip_forward.conf
    contents: 'net.ipv4.ip_forward = 1'
```
But this now fails because it cannot `touch` the `/etc/sysctl.d/01-ip_forward.conf` target.

I could workaround this by adding `readonly: false` in the appropriate place however I'm not sure if that is the best solution.

Better/preferable alternatives might include:
* Have the moby tool spot the need to make these files (or sometimes directories) and do it statically when building the image.
* Always create a rw rootfs and rely on runc to remount it ro (based on what is in `config.json`) if that is what we want. (As was done in https://github.com/kubernetes-incubator/cri-containerd/pull/221)
* Add an empty `50-custom.conf` file to the `sysctl` image as a target for such a mount

Not sure if there are any others.
