### ISSUE TITLE
Minimal custom init image

### ISSUE THREAD

**Issue by pwFoo** [linuxkit/linuxkit#2505]
Hi,

for testing I try to build a custom (minimal) init image which just starts a shell. No onboot / services so far.
Just busybox init to start a shell.
```
kernel:
  image: linuxkit/kernel:4.9.47
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - myrepo/init:latest
```

After booting the build it boots up to my "Boot finished" line, but I don't reach the shell.
To understand how linuxkit works. What is needed to get a shell with my example?
