### ISSUE TITLE
Okernel fails to boot on packet.net

### ISSUE THREAD

**Issue by Sh4d1** [linuxkit/linuxkit#2576]
**Description**
Hey! I wanted to test the Okernel with LinuxKit on packet.net however it seems to freeze just before I can access the shell.

**Steps to reproduce the issue:**
I have this packet.yml file : 
```yml
kernel:
  image: okernel:latest
  cmdline: "console=tty0 console=ttyS1 console=ttyAMA0 page_poison=1"                    
init:
  - linuxkit/init:7804129bd06218b72c298139a25698a748d253c6
  - linuxkit/runc:a1b564248a0d0b118c11e61db9f84ecf41dd2d2a
  - linuxkit/containerd:417f83f7b8dc1fa36acf90effe44f99c7397480a
  - linuxkit/ca-certificates:e44b0a66df5a102c0e220f0066b0d904710dcb10                    
onboot:
  - name: rngd1                                                                              
    image: linuxkit/rngd:558e86a36242bb74353bc9287b715ddb8567357e
    command: ["/sbin/rngd", "-1"]
  - name: sysctl
    image: linuxkit/sysctl:154913b72c6f1f33eb408609fca9963628e8c051                        
  - name: dhcpcd
    image: linuxkit/dhcpcd:d4408777ed6b6e6e562a5d4938fd09804324b33e
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:da3138079c168e0c5608d8f3853366c113ed91d2
    command: ["/usr/bin/metadata", "packet"]
services:
  - name: rngd
    image: linuxkit/rngd:558e86a36242bb74353bc9287b715ddb8567357e
  - name: sshd
    image: linuxkit/sshd:361e9d03f96ef5f22e61c69280ffb9291bde746f
files:
  - path: root/.ssh/authorized_keys
    source: /home/patrik/.ssh/id_rsa.pub
    mode: "0600"
    optional: false
trust:
  org:
    - linuxkit
```
I build it with `moby build packet.yml` with the okernel built as mentioned on the README. 
Then I launch a packet instance with the linuxkit `PACKET_API_KEY=... linuxkit run packet  -base-url http://8e1a7dc9.ngrok.io -project-id ... packet` whith ngrok and nginx already running.

**Describe the results you received:**
Here is all the boot code I get : 
[Pastebin llink](https://pastebin.com/XhEUBCyY)
And it freezes right here, I can do nothing.
**Describe the results you expected:**
I expected to have a working shell

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by richardj-bsquare** [comment]
When you say freeze, do you mean, that SSH freezes? Or do you mean you don't have a login on the console? If the latter that'll be because you don't a getty service running to handle the 'shell'.

**Comment by Sh4d1** [comment]
I think ssh freezes, when I try to connect via ssh it does not work, I don't actually remember if the port was closed or not.. As for Getty I tried with it if I'm right, I had the same problem. I will try again when I have some time, I'll post the output as well.

**Comment by Sh4d1** [comment]
Okay, so here is my new packet.yml
```yaml
kernel:
  image: okernel:latest
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 page_poison=1"                                        
init:
  - linuxkit/init:7804129bd06218b72c298139a25698a748d253c6
  - linuxkit/runc:a1b564248a0d0b118c11e61db9f84ecf41dd2d2a
  - linuxkit/containerd:417f83f7b8dc1fa36acf90effe44f99c7397480a
  - linuxkit/ca-certificates:e44b0a66df5a102c0e220f0066b0d904710dcb10                                        onboot:
  - name: rngd1                                                                                                  
    image: linuxkit/rngd:558e86a36242bb74353bc9287b715ddb8567357e
    command: ["/sbin/rngd", "-1"]
  - name: sysctl
    image: linuxkit/sysctl:154913b72c6f1f33eb408609fca9963628e8c051                                            - name: dhcpcd
    image: linuxkit/dhcpcd:d4408777ed6b6e6e562a5d4938fd09804324b33e
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:da3138079c168e0c5608d8f3853366c113ed91d2
    command: ["/usr/bin/metadata", "packet"]
services:
  - name: rngd
    image: linuxkit/rngd:558e86a36242bb74353bc9287b715ddb8567357e
  - name: sshd
    image: linuxkit/sshd:361e9d03f96ef5f22e61c69280ffb9291bde746f
  - name: getty
    image: linuxkit/getty:a19851531487b7bfbe45dcf77e3309c127cc78a6
    env:
      - INSECURE=true
files:
  - path: root/.ssh/authorized_keys
    source: /home/patrik/.ssh/id_rsa.pub
    mode: "0600"
    optional: false
  - path: etc/getty.shadow
    contents: 'root:$6$6tPd2uhHrecCEKug$8mKfcgfwguP7f.BLdZsT1Wz7WIIJOBY1oUFHzIv9/O71M2J0EPdtFqFGTxB1UK5ejqQxRFQ.ZSG9YXR0SNsc11:17322:0:::::'
trust:
  org:
    - linuxkit
```

Here is the [serial output ](https://pastebin.com/hM44dQcG)

Here is the output of nmap:
```
nmap 147.75.100.1 -Pn

Starting Nmap 7.60 ( https://nmap.org ) at 2017-10-10 11:04 CEST
Nmap scan report for patrik-linuxkit (147.75.100.1)
Host is up (0.0011s latency).
Not shown: 997 filtered ports
PORT     STATE  SERVICE
113/tcp  closed ident
8008/tcp open   http
8010/tcp closed xmpp

Nmap done: 1 IP address (1 host up) scanned in 4.74 seconds
```

And here is the ssh log when I try to connect : 
```
ssh -vvv root@147.75.100.1
OpenSSH_7.6p1, OpenSSL 1.1.0f  25 May 2017
debug1: Reading configuration data /etc/ssh/ssh_config
debug2: resolving "147.75.100.1" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 147.75.100.1 [147.75.100.1] port 22.
debug1: connect to address 147.75.100.1 port 22: Connection timed out
ssh: connect to host 147.75.100.1 port 22: Connection timed out
```

**Comment by justincormack** [comment]
ping @t-koulouris

**Comment by t-koulouris** [comment]
Hi,

We haven't tested whether the current builds of okernel run on packet.net - let me investigate and I will report back.

**Comment by t-koulouris** [comment]
Hello again,

Apologies for the delay but I wanted to be thorough (plus, I had issues getting a webserver to punch through the corporate firewall to serve the files).

That said, I wasn't able to replicate your issue.

As you can see from the output excerpt below, getty gave me a shell as expected:
```
[   10.579946] sd 3:0:0:0: [sdb] Attached SCSI disk
[   10.626089] sd 2:0:0:0: [sda] Write Protect is off
[   10.631220] sd 2:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[   10.644918] sd 2:0:0:0: [sda] Attached SCSI disk

Welcome to LinuxKit

                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
          {                       /  ===-
           \______ O           __/
             \    \         __/
              \____\_______/


(none) login: root (automatic login)

Welcome to LinuxKit!

NOTE: This system is namespaced.
The namespace you are currently in may not be the root.
(ns: getty) (none):~# ls
(ns: getty) (none):~# cd /
(ns: getty) (none):/# cd containers/services
(ns: getty) (none):/containers/services# uname -a
Linux (none) 4.14.0-rc1 #1 SMP Wed Oct 11 12:17:13 UTC 2017 x86_64 Linux
(ns: getty) (none):/containers/services# cat /proc/self/okernel 
0
```


I used a Type 1 server in AMS1. I hadn't used packet before and it took me a few tries to get the SOS console going.

In addition, I tested the same okernel image (just in case) in the following:
1) Baremetal on local workstation ('raw' image, boot from USB stick)
2) As a VMWare VM (vmdk output - got shell, didn't test okernel features due to lack of nested virtualisation support)

In both cases Linuxkit booted fine and I got a shell.

I would suggest if you have the time to test using the okernel_simple.yaml file under projects/okernel/examples and if you still experience the same issue we'll take it from there.

**Comment by Sh4d1** [comment]
Hmm, I thought I tried the okernel_simple.yaml, but when I tried this time it worked. So I started to add one service at the time to get the original yaml file I had, and the problem since to be with dhcpcd on the onboot section. 

So here is a working yaml config: 
```yaml
kernel:
  image: okernel:latest
  cmdline: "console=tty0 page_poison=1"                                                                      
init:
  - linuxkit/init:7804129bd06218b72c298139a25698a748d253c6
  - linuxkit/runc:a1b564248a0d0b118c11e61db9f84ecf41dd2d2a
  - linuxkit/containerd:417f83f7b8dc1fa36acf90effe44f99c7397480a
  - linuxkit/ca-certificates:e44b0a66df5a102c0e220f0066b0d904710dcb10                                        onboot:
  - name: rngd1                                                                                                  
    image: linuxkit/rngd:558e86a36242bb74353bc9287b715ddb8567357e
    command: ["/sbin/rngd", "-1"]
  - name: sysctl
    image: linuxkit/sysctl:154913b72c6f1f33eb408609fca9963628e8c051                                            - 
  - name: metadata                                                                                               
    image: linuxkit/metadata:da3138079c168e0c5608d8f3853366c113ed91d2
    command: ["/usr/bin/metadata", "packet"]
services:
  - name: rngd
    image: linuxkit/rngd:558e86a36242bb74353bc9287b715ddb8567357e
  - name: getty
    image: linuxkit/getty:a19851531487b7bfbe45dcf77e3309c127cc78a6
    env:
      - INSECURE=true
  - name: sshd
    image: linuxkit/sshd:361e9d03f96ef5f22e61c69280ffb9291bde746f
files:
  - path: root/.ssh/authorized_keys
    source: /home/patrik/.ssh/id_rsa.pub
    mode: "0600"
    optional: false
trust:                                                                                                         
  org:
    - linuxkit
```
And here is how I reproduce the issue:
```yaml
kernel:
  image: okernel:latest
  cmdline: "console=tty0 page_poison=1"                                                                      
init:
  - linuxkit/init:7804129bd06218b72c298139a25698a748d253c6
  - linuxkit/runc:a1b564248a0d0b118c11e61db9f84ecf41dd2d2a
  - linuxkit/containerd:417f83f7b8dc1fa36acf90effe44f99c7397480a
  - linuxkit/ca-certificates:e44b0a66df5a102c0e220f0066b0d904710dcb10                                        onboot:
  - name: rngd1                                                                                                  
    image: linuxkit/rngd:558e86a36242bb74353bc9287b715ddb8567357e
    command: ["/sbin/rngd", "-1"]
  - name: sysctl
    image: linuxkit/sysctl:154913b72c6f1f33eb408609fca9963628e8c051                                            - 
  - name: dhcpcd                                                                                                 
    image: linuxkit/dhcpcd:d4408777ed6b6e6e562a5d4938fd09804324b33e
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata                                                                                               
    image: linuxkit/metadata:da3138079c168e0c5608d8f3853366c113ed91d2
    command: ["/usr/bin/metadata", "packet"]
services:
  - name: rngd
    image: linuxkit/rngd:558e86a36242bb74353bc9287b715ddb8567357e
  - name: getty
    image: linuxkit/getty:a19851531487b7bfbe45dcf77e3309c127cc78a6
    env:
      - INSECURE=true
  - name: sshd
    image: linuxkit/sshd:361e9d03f96ef5f22e61c69280ffb9291bde746f
files:
  - path: root/.ssh/authorized_keys
    source: /home/patrik/.ssh/id_rsa.pub
    mode: "0600"
    optional: false
trust:                                                                                                         
  org:
    - linuxkit
```

But when I try to run it with the basic kernel it works. So I guess it is linked to the okernel but I'm not sure. What do you think ?
