### ISSUE TITLE
Proposal: Direct file insert into containers

### ISSUE THREAD

**Issue by deitch** [linuxkit/linuxkit#2618]
Currently, we mount files directly onto the host, and then from there bind-mount into the `onboot` or `services` containers, e.g. the compose file snippet in the below sample from `projects/compose/`:

```yml
services:
  - name: compose
    image: linuxkitprojects/compose:0535e78608f57702745dfd56fbe78d28d237e469
    binds:
     - /var/run:/var/run
     - /etc/compose:/compose
files:
  - path: etc/compose/docker-compose.yml
    source: docker-compose.yml
```

This has several issues:

* files intended for one container are bindable by another (primarily by accident)
* files can trounce one another
* files can be mounted in a place that we might later changes, e.g. `/var` used to be _the_ read-write place for everything, including mounting, but then became tmpfs, so files copied there aren't visible
* it confuses files needed for the host itself (which should be almost nothing) with those required in a container

This is a discussion to attempt to tackle that.

First cut is to have a `files:` option _inside_ a container config, e.g.:

```yml
services:
  - name: compose
    image: linuxkitprojects/compose:0535e78608f57702745dfd56fbe78d28d237e469
    binds:
     - /var/run:/var/run
    files:
     - path: /etc/compose/docker-compose.yml
        source: docker-compose.yml
  - name: sshd
     image: linuxkit/sshd:4a2fc7be31fa57dcade391de6173e0af55296e7f
     files:
       - path: /root/.ssh/authorized_keys
         source: ~/.ssh/id_rsa.pub
         mode: "0600"
         optional: true
```

The above would place the file `docker-compose.yml` from the current dir into `/etc/compose/docker-compose.yml` _inside_ the `compose` container. Similarly, the file on the build host `~/.ssh/id_rsa.pub` would bee placed in `/root/.ssh/authorized_keys` _inside_ the `sshd` container.

If we used the above, then `files:` as a top-level key of a moby `.yml` would be used _only_ for files to be used by the host itself (which normally would be nothing or almost nothing.

I find this much cleaner than doing the "files two-step" which loads it into the image and then bind-mounts into the container. It also helps with some of the "bind-mounts override LABEL defaults" issue (but doesn't solve it).

The only issue I see would be if you want a single file or dir shared between multiple containers, but I am content to start with this as a first step. Most cases are single files read-only anyways, even if shared.

From an implementation perspective, I would have a dedicated directory for mounts to containers, probably something like `/.containerfiles/<container_name>/` where individual files or directories are placed and then bind-mounted in. I think I would then _prevent_ `/.containerfiles` (or whatever path is chosen) from being mountable in the `binds` list, so no one is tempted to mount it directly. 

Open for discussion.

**Comment by deitch** [comment]
I was thinking a bit about a potential slightly different approach, one closer to the current, which could enable sharing files across containers but not exposing them to the base OS:

```yml
services:
  - name: compose
    image: linuxkitprojects/compose:0535e78608f57702745dfd56fbe78d28d237e469
    files:
     - compose.yml:/etc/compose/docker-compose.yml
     - foo: /etc/foo.txt
files:
  - name: compose.yml
    source: docker-compose.yml
  - name: foo
    content: "abc\n"
```

The above allows them to be mounted into multiple containers. It is somewhat inspired by data volume containers: don't load content to the filesystem. Instead, give chunks of content (files) a unique name, and then bind that name into the container.
