### ISSUE TITLE
Proposal: package managment

### ISSUE THREAD

**Issue by w9n** [linuxkit/linuxkit#2674]
Coming from #2648 and moby/tool#101, I would like to propose a more complete package management system. 

Requirments:

**- remove hashes for users**
  Hashes in moby files should be replaced by ```:mutable``` or ```:latest``` and only appear in artifacts or pinning down of versions for usability and maintainability.
**- real image hashes over git source hashes as image tags**
container pull latest packages from e.g. alpine on build time and therefore should update to latest dependencies with new hashes.
**- use git hashes for CI**
CI should build, test and push as soon as possible but dont do everything on every merge. Therefore it has to know which package has changed. 
**- decoupling from registry**
remove registry information from linuxkit yml and make it plug and play with a package repository.  

This leads to the following data structure of a linuxkit package repository, where  CI can check the git hashes on every Pull and work on timestamps  to build/test/push images:

```
Repository: linuxkit #registry name (high dependency between this file and registry content)
Packages:
  - pkg_A: #package name
    source_location: /path/to/package
      - pkg_root_hash: afb7c111a40788b1e085856fbddacf8a878385e7 # git hash
      version: v2.0 #from build.yml in pkg dir
      architecture:
        - X86:
          - <real_hash_of_Image>:
            - <timestamp_of_first_build>
          - <real_hash_of_Image>:
            - <timestamp_of_last_build>
            - <timestamp_of_first_build>
        - ARM:
         ....
    - pkg_root_hash: 42a92119e1ca10380e0d33e26c0cbcf85b9b3558 # A previous commit
    version: v1.0
    architecture:
      - X86
        - <old_hash_of_Image>
          ...
  -pkg_B:  
  ....
```
These information can then be used in moby to transform a registry independent template:
<details>

```

kernel:
  image: linuxkit/kernel:4.9.58
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - init:mutable
  - runc:mutable
  - containerd:42a92119e1ca10380e0d33e26c0cbcf85b9b3558
  - ca-certificates:mutable
onboot:
  - name: sysctl
    image: sysctl:v3
  - name: rngd1
    image: rngd:v2
    command: ["/sbin/rngd", "-1"]
services:
  - name: getty
    image: getty:mutable
    env:
     - INSECURE=true
  - name: rngd
    image: rngd:v2
  - name: dhcpcd
    image: dhcpcd:mutable
  - name: sshd
    image: sshd:mutable
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
trust:
  org:
    - linuxkit

```

</details>
into many platform and registry specific real immutable manifests, which can be easily compared and rolled back.
<details>

```

kernel:
  image: linuxkit/kernel:4.9.58
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
    #<git_hash>
    #<timestamp_of_build>
  - linuxkit/init:42a92119e1ca10380e0d33e26c0cbcf85b9b3558
    #<git_hash>
    #<timestamp_of_build>
  - linuxkit/runc:817fdc592eac6cb7804fa1721a43a7f6e23fb50f
    #<git_hash>
    #<timestamp_of_build>
  - linuxkit/containerd:42a92119e1ca10380e0d33e26c0cbcf85b9b3558
    #<git_hash>
    #<timestamp_of_build>
  - linuxkit/ca-certificates:af4880e78edc28743f7c5e262678c67c6add4c26
onboot:
  - name: sysctl
    #<git_hash>
    #<timestamp_of_build>
    image: linuxkit/sysctl:a9ad57ed738a31ea9380cd73236866c312b35489
  - name: rngd1
    #<git_hash>
    #<timestamp_of_build>
    image: linuxkit/rngd:842e5e8ece7934f0cab9fd0027b595ff3471e5b9
    command: ["/sbin/rngd", "-1"]
services:
  - name: getty
    #<git_hash>
    #<timestamp_of_build>
    image: linuxkit/getty:626ccc8e1766c40447f29a790d3a7cfff126f2a2
    env:
     - INSECURE=true
  - name: rngd
    #<git_hash>
    #<timestamp_of_build>
    image: linuxkit/rngd:842e5e8ece7934f0cab9fd0027b595ff3471e5b9
  - name: dhcpcd
    #<git_hash>
    #<timestamp_of_build>
    image: linuxkit/dhcpcd:48831507404049660b960e4055f544917d90378e
  - name: sshd
    #<git_hash>
    #<timestamp_of_build>
    image: linuxkit/sshd:f55ec010619e19178d5daecb4e595e84ecbf7d67
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
trust:
  org:
    - linuxkit

```

</details>
