### ISSUE TITLE
Docker image containing glibc binary causes services to fail startup

### ISSUE THREAD

**Issue by sjtindell** [linuxkit/linuxkit#2697]
**Description**

Copying a glibc binary to a Docker image then using that image in a linuxkit build causes services to fail to start or setup proper OCI configs when booted via HyperKit. Booting via Virtualbox works as expected.

Removing the line from the DOCKERFILE where we COPY the binary into the image removes the issue and all containers have OCI configs + start as expected.

**Steps to reproduce the issue:**
```
[images/test]-> linuxkit version
linuxkit version 0.0
commit: 239a82901edcd24cf31a70089313e72c8fc9f4a6
[images/test]-> moby version
moby version 0.0
commit: 76035cec2f9d6176fea800b7f5f10ef8e19f90b8
[images/test]-> docker --version
Docker version 17.06.2-ce, build cec0b72
```

Setup a Docker image directory.
```
[pkg/testimage]-> ls
Dockerfile bin
[pkg/testimage]-> file bin/kubelet
bin/kubelet: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=b0b5e64527188c65820f3831b6c79e8b57c4ddc3, with debug_info, not stripped
```
Get the kubelet binary and place it in the `bin` folder.
https://kubernetes.io/docs/getting-started-guides/scratch/

> Download the latest binary release and unzip it. Server binary tarballs are no longer included in the Kubernetes final tarball, so you will need to locate and run ./kubernetes/cluster/get-kube-binaries.sh to download the client and server binaries. Then locate ./kubernetes/server/kubernetes-server-linux-amd64.tar.gz and unzip that. Then, within the second set of unzipped files, locate ./kubernetes/server/bin, which contains all the necessary binaries.

Move the kubelet binary from kubernetes/server/bin to bin in your Dockerfile directory.

DOCKERFILE contents.
```
FROM linuxkit/alpine:0fb5b5e7952d22eeae57607493168e679a4a0c0a AS mirror

RUN mkdir -p /out/etc/apk && cp -r /etc/apk/* /out/etc/apk/
RUN apk add --no-cache --initdb -p /out \
    alpine-baselayout \
    apk-tools \
    ca-certificates \
    util-linux \
    wireguard-tools \
    && true

RUN mv /out/etc/apk/repositories.upstream /out/etc/apk/repositories


FROM scratch
ENTRYPOINT []
WORKDIR /
COPY --from=mirror /out/ /
COPY bin/kubelet /usr/bin/kubelet

CMD ["tail", "-f", "/dev/null"]
LABEL org.mobyproject.config='{"pid": "host", "capabilities": ["all"]}'

```
Build the Docker image.
```
[pkg/testimage]-> docker build . -t myorg/testimage
........
Successfully built e10906ac8780
Successfully tagged myorg/testimage:latest
```
Create a custom yml file by adding your image to the docker.yml example file.
```

kernel:
  image: linuxkit/kernel:4.9.59
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:42a92119e1ca10380e0d33e26c0cbcf85b9b3558
  - linuxkit/runc:817fdc592eac6cb7804fa1721a43a7f6e23fb50f
  - linuxkit/containerd:82be2bbb7cf83bab161ffe2a64624ba1107725ff
  - linuxkit/ca-certificates:af4880e78edc28743f7c5e262678c67c6add4c26
onboot:
  - name: sysctl
    image: linuxkit/sysctl:a9ad57ed738a31ea9380cd73236866c312b35489
  - name: sysfs
    image: linuxkit/sysfs:5367b46211882278b84a9e8048855ca5df65beda
  - name: format
    image: linuxkit/format:10e75e78e1f134d310c62e9a0352df1c67b0dd81
  - name: mount
    image: linuxkit/mount:41685ecc8039643948e5dff46e17584753469a7a
    command: ["/usr/bin/mountie", "/var/lib/docker"]
services:
  - name: getty
    image: linuxkit/getty:626ccc8e1766c40447f29a790d3a7cfff126f2a2
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:842e5e8ece7934f0cab9fd0027b595ff3471e5b9
  - name: dhcpcd
    image: linuxkit/dhcpcd:48831507404049660b960e4055f544917d90378e
  - name: ntpd
    image: linuxkit/openntpd:07a80c3e3e816658318ac027e1253ff9a228b8de
  - name: docker
    image: docker:17.07.0-ce-dind
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /var/lib/docker:/var/lib/docker
     - /lib/modules:/lib/modules
     - /etc/docker/daemon.json:/etc/docker/daemon.json
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
  - name: myservice
    image: myorg/testimage
files:
  - path: var/lib/docker
    directory: true
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
trust:
  org:
    - linuxkit
    - library
```
Build the initrd and kernel.
```
[images/test]-> moby build custom.yml
.........
Created outputs.
```
Run via linuxkit.
`[images/test]-> linuxkit run custom`

Build a tarball version.
`[images/test]-> moby build -format tar custom.yml`

**Describe the results you received:**
When `linuxkit run` starts the image via hyperkit neither docker nor myservice start successfully per output of `ctr t`.
myservice does not have any OCI configs present under `/containers/services/myservice`.
But the OCI configs are present in a tarball output from moby build.
The kubelet binary is also present in the unpacked tarball.

On the hyperkit VM.
```
(ns: getty) linuxkit-025000000010:~# ctr t
TASK      PID    STATUS
rngd      649    RUNNING
dhcpcd    467    RUNNING
getty     556    RUNNING
ntpd      608    RUNNING
(ns: getty) linuxkit-025000000010:~# ls /containers/services/docker/
config.json   lower         rootfs        runtime.json  tmp
(ns: getty) linuxkit-025000000010:~# ls /containers/services/myservice/
lower
(ns: getty) linuxkit-025000000010:~# runc run --bundle /containers/services/docker docker
container_linux.go:295: starting container process caused "process_linux.go:280: applying cgroup configuration for process caused \"mkdir /sys/fs/cgroup/cpuset/getty: read-only file system\""
```

In the tarball
```
[test/store]-> ls
bin        containers dev        home       lib        mnt        root       sbin       sys        usr
boot       custom.tar etc        init       media      proc       run        srv        tmp        var
[test/store]-> ls containers/services/myservice
config.json  lower        rootfs       runtime.json tmp
[test/store]-> ls containers/services/docker
config.json  lower        rootfs       runtime.json tmp
[test/store]-> file containers/services/myservice/lower/usr/bin/kubelet
containers/services/myservice/lower/usr/bin/kubelet: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=b0b5e64527188c65820f3831b6c79e8b57c4ddc3, with debug_info, not stripped
```

Build the VHD
`moby build -format vhd custom.yml`

Boot it via VirtualBox.
In the Virtualbox VM we see the following.
```
(ns: getty) linuxkit-025000000011:~# ctr t
TASK         PID    STATUS
docker       537    RUNNING
getty        580    RUNNING
myservice    632    RUNNING
ntpd         667    RUNNING
rngd         709    RUNNING
dhcpcd       466    RUNNING
(ns: getty) linuxkit-025000000011:~# ls /containers/services/docker/
config.json   lower         rootfs        runtime.json  tmp
(ns: getty) linuxkit-025000000011:~# ls /containers/services/myservice/
config.json   lower         rootfs        runtime.json  tmp
```

**Describe the results you expected:**
Both docker and myservice container would start, the OCI configs would be present and the kubelet binary would be present.

**Additional information you deem important (e.g. issue happens only occasionally):**
Simply removing the the line from the DOCKERFILE in which we perform the COPY gives us the following output in the hyperkit VM when performing a `linuxkit run custom` using all the other configs. 
```
(ns: getty) linuxkit-025000000011:~# ctr t
TASK         PID    STATUS
docker       537    RUNNING
getty        580    RUNNING
myservice    632    RUNNING
ntpd         667    RUNNING
rngd         709    RUNNING
dhcpcd       466    RUNNING
(ns: getty) linuxkit-025000000011:~# ls /containers/services/docker/
config.json   lower         rootfs        runtime.json  tmp
(ns: getty) linuxkit-025000000011:~# ls /containers/services/myservice/
config.json   lower         rootfs        runtime.json  tmp
```
