### ISSUE TITLE
vpnkit not working with kernel 4.4.96

### ISSUE THREAD

**Issue by dprotaso** [linuxkit/linuxkit#2698]
**Description**

VPNKit doesn't seem to work with linuxkit/kernel:4.4.96

**Steps to reproduce the issue:**

Using the following example.yml
```
kernel:
  image: linuxkit/kernel:4.4.96
  cmdline: "console=ttyS0"

init:
  - linuxkit/init:42a92119e1ca10380e0d33e26c0cbcf85b9b3558
  - linuxkit/runc:817fdc592eac6cb7804fa1721a43a7f6e23fb50f
  - linuxkit/containerd:82be2bbb7cf83bab161ffe2a64624ba1107725ff
  - linuxkit/getty:626ccc8e1766c40447f29a790d3a7cfff126f2a2

onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:48831507404049660b960e4055f544917d90378e
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]

  - name: mount-vpnkit
    image: alpine:3.6
    binds:
        - /var/:/host_var:rbind,rshared
    capabilities:
        - CAP_SYS_ADMIN
    rootfsPropagation: shared
    command: ["sh", "-c", "mkdir /host_var/vpnkit && mount -v -t 9p -o trans=virtio,dfltuid=1001,dfltgid=50,version=9p2000 port /host_var/vpnkit"]

services:  
  - name: vpnkit-forwarder
    image: linuxkit/vpnkit-forwarder:c7e61d9250de0b21455dc5c8bb885bd8faa31621
    binds:
        - /var/vpnkit:/port
    net: host
    command: ["/vpnkit-forwarder"]


  - name: nginx
    image: nginx:alpine
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE

  - name: vpnkit-expose-port
    image: linuxkit/vpnkit-expose-port:15c56c57ac9a7adeec20b34f36f2bc165c347679
    net: none
    binds:
        - /var/vpnkit:/port
    command: ["/usr/bin/vpnkit-expose-port","-i",
              "-host-ip","127.0.0.1","-host-port","8080",
              "-container-ip","127.0.0.1","-container-port","80","-no-local-ip"]
trust:
  org:
    - linuxkit
```

Build and run
```
# moby build example.yml
# linuxkit run hyperkit -networking=vpnkit example
# curl -v localhost:8080
```

**Describe the results you received:**

VM starts but curling hangs
```
$ curl -v localhost:8080
* Rebuilt URL to: localhost:8080/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
>
```

**Describe the results you expected:**

If you change the kernel to 4.9.60 curling will return

```
$ curl -v localhost:8080
* Rebuilt URL to: localhost:8080/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.13.5
< Date: Wed, 08 Nov 2017 01:36:28 GMT
< Content-Type: text/html
< Content-Length: 612
< Last-Modified: Wed, 13 Sep 2017 17:15:56 GMT
< Connection: keep-alive
< ETag: "59b967cc-264"
< Accept-Ranges: bytes
<
<!DOCTYPE html>
<html>
...
</html>
```
