### ISSUE TITLE
/var/lib/host directory is not being created via files section?

### ISSUE THREAD

**Issue by tristanls** [linuxkit/linuxkit#2711]
**Description**
I don't understand why directory specified in `files` section of configuration is not being created.

**Steps to reproduce the issue:**
Dockerfile:
```
FROM alpine:3.6

ENTRYPOINT /bin/echo "hi" > /var/lib/scratchpad/file.txt
```
Built with `docker build -t local/scratchpad:0.0.0 .`
Configuration file `machine.yaml`:
```
kernel:
  image: linuxkit/kernel:4.9.61
  cmdline: "console=ttyS0"
init:
  - linuxkit/init:42a92119e1ca10380e0d33e26c0cbcf85b9b3558
  - linuxkit/runc:817fdc592eac6cb7804fa1721a43a7f6e23fb50f
  - linuxkit/containerd:82be2bbb7cf83bab161ffe2a64624ba1107725ff
  - linuxkit/ca-certificates:af4880e78edc28743f7c5e262678c67c6add4c26
onboot:
  - name: sysctl
    image: linuxkit/sysctl:a9ad57ed738a31ea9380cd73236866c312b35489
  - name: dhcpcd
    image: linuxkit/dhcpcd:48831507404049660b960e4055f544917d90378e
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: rngd
    image: linuxkit/rngd:842e5e8ece7934f0cab9fd0027b595ff3471e5b9
  - name: getty
    image: linuxkit/getty:626ccc8e1766c40447f29a790d3a7cfff126f2a2
    env:
     - INSECURE=true
  - name: scratchpad
    image: local/scratchpad:0.0.0
    binds:
      - /var/lib/host:/var/lib/scratchpad
files:
  - path: var/lib/host
    directory: true
  - path: etc/containerd/config.toml
    contents: |
      state = "/run/containerd"
      root = "/var/lib/containerd"
      snapshotter = "io.containerd.snapshotter.v1.overlayfs"
      differ = "io.containerd.differ.v1.base-diff"
      subreaper = false

      [grpc]
      address = "/run/containerd/containerd.sock"
      uid = 0
      gid = 0
trust:
  org:
    - linuxkit
    - library
```
Built with `moby build machine.yaml`.
Run with `linuxkit run machine`.

**Describe the results you received:**
Observed:
```
...
ERRO[0000] failed to create task                         error="OCI runtime create failed: container_linux.go:295: starting container process caused "process_linux.go:399: container init caused \"rootfs_linux.go:57: mounting \\\"/var/lib/host\\\" to rootfs \\\"/containers/services/scratchpad/rootfs\\\" at \\\"/var/lib/scratchpad\\\" caused \\\"stat /var/lib/host: no such file or directory\\\"\"": unknown"
```

**Describe the results you expected:**
I expected `/var/lib/host` to have been created via:
```
...
files:
  - path: var/lib/host
    directory: true
...
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by tristanls** [comment]
Observing the same issue after updating to latest `linuxkit/*` packages:
```
kernel:
  image: linuxkit/kernel:4.9.61
  cmdline: "console=ttyS0"
init:
  - linuxkit/init:b3b75c18d82fb32b978c7d837fc896dafffd3a63
  - linuxkit/runc:817fdc592eac6cb7804fa1721a43a7f6e23fb50f
  - linuxkit/containerd:bfb61cc1d26c39cd4b2bc08f7a9963fefa0ef3bf
  - linuxkit/ca-certificates:af4880e78edc28743f7c5e262678c67c6add4c26
onboot:
  - name: sysctl
    image: linuxkit/sysctl:a9ad57ed738a31ea9380cd73236866c312b35489
  - name: dhcpcd
    image: linuxkit/dhcpcd:48831507404049660b960e4055f544917d90378e
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: rngd
    image: linuxkit/rngd:842e5e8ece7934f0cab9fd0027b595ff3471e5b9
  - name: getty
    image: linuxkit/getty:6af22c32c98536a79230eef000e9abd06b037faa
    env:
     - INSECURE=true
  - name: scratchpad
    image: local/scratchpad:0.0.0
    binds:
      - /var/lib/host:/var/lib/scratchpad
files:
  - path: var/lib/host
    directory: true
  - path: etc/containerd/config.toml
    contents: |
      state = "/run/containerd"
      root = "/var/lib/containerd"
      snapshotter = "io.containerd.snapshotter.v1.overlayfs"
      differ = "io.containerd.differ.v1.base-diff"
      subreaper = false

      [grpc]
      address = "/run/containerd/containerd.sock"
      uid = 0
      gid = 0
trust:
  org:
    - linuxkit
    - library
```

**Comment by tristanls** [comment]
For reasons I don't quite understand `var` directory is treated differently. This `machine.yaml` does what I expected. Had to use `runtime` with `mkdir` section:
```
kernel:
  image: linuxkit/kernel:4.9.61
  cmdline: "console=ttyS0"
init:
  - linuxkit/init:b3b75c18d82fb32b978c7d837fc896dafffd3a63
  - linuxkit/runc:817fdc592eac6cb7804fa1721a43a7f6e23fb50f
  - linuxkit/containerd:bfb61cc1d26c39cd4b2bc08f7a9963fefa0ef3bf
  - linuxkit/ca-certificates:af4880e78edc28743f7c5e262678c67c6add4c26
onboot:
  - name: sysctl
    image: linuxkit/sysctl:a9ad57ed738a31ea9380cd73236866c312b35489
  - name: dhcpcd
    image: linuxkit/dhcpcd:48831507404049660b960e4055f544917d90378e
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: rngd
    image: linuxkit/rngd:842e5e8ece7934f0cab9fd0027b595ff3471e5b9
  - name: getty
    image: linuxkit/getty:6af22c32c98536a79230eef000e9abd06b037faa
    env:
     - INSECURE=true
  - name: scratchpad
    image: local/scratchpad:0.0.0
    binds:
      - /var/lib/host:/var/lib/scratchpad
    runtime:
      mkdir:
        - /var/lib/host
files:
  - path: etc/containerd/config.toml
    contents: |
      state = "/run/containerd"
      root = "/var/lib/containerd"
      snapshotter = "io.containerd.snapshotter.v1.overlayfs"
      differ = "io.containerd.differ.v1.base-diff"
      subreaper = false

      [grpc]
      address = "/run/containerd/containerd.sock"
      uid = 0
      gid = 0
trust:
  org:
    - linuxkit
    - library
```
