### ISSUE TITLE
"linuxkit run" and RAM requirements

### ISSUE THREAD

**Issue by mmariani** [linuxkit/linuxkit#2713]
**Description**

When deploying an image, if the VM does not have enough RAM some of the data under /containers/services/docker/ directory may be missing. The image file itself contains all the data, but it's not available to the VM.

The resulting behavior is unpredictable: services may not be running or not find configuration data.

**Steps to reproduce the issue:**

Given this template:

```
kernel:
  image: linuxkit/kernel:4.9.60
  cmdline: "console=tty0 console=ttyS0 page_poison=1"
init:
  - linuxkit/init:42a92119e1ca10380e0d33e26c0cbcf85b9b3558
  - linuxkit/runc:817fdc592eac6cb7804fa1721a43a7f6e23fb50f
  - linuxkit/containerd:bfb61cc1d26c39cd4b2bc08f7a9963fefa0ef3bf
  - linuxkit/ca-certificates:af4880e78edc28743f7c5e262678c67c6add4c26
onboot:
  - name: sysctl
    image: linuxkit/sysctl:a9ad57ed738a31ea9380cd73236866c312b35489
  - name: dhcpcd
    image: linuxkit/dhcpcd:48831507404049660b960e4055f544917d90378e
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:9506d124d0a3ff645c9781c47f207423abf6154d
    command: ["/usr/bin/metadata", "openstack"]
  - name: sysfs
    image: linuxkit/sysfs:5367b46211882278b84a9e8048855ca5df65beda
  - name: format
    image: linuxkit/format:10e75e78e1f134d310c62e9a0352df1c67b0dd81
  - name: mount
    image: linuxkit/mount:41685ecc8039643948e5dff46e17584753469a7a
    command: ["/usr/bin/mountie", "/var/lib/docker"]

services:

  - name: getty
    image: linuxkit/getty:6af22c32c98536a79230eef000e9abd06b037faa
    env:
      - INSECURE=false
    binds:
      - /etc/securetty:/etc/securetty
      - /etc/resolv.conf:/etc/resolv.conf
      - /run:/run
      - /tmp:/tmp
      - /etc:/hostroot/etc
      - /etc/passwd:/etc/passwd
      - /usr/bin/ctr:/usr/bin/ctr
      - /usr/bin/runc:/usr/bin/runc
      - /containers:/containers
      - /var/log:/var/log
      - /dev:/dev
      - /sys:/sys

  - name: docker
    image: docker:17.10.0-ce-dind
    capabilities:
      - all
    net: host
    mounts:
      - type: cgroup
        options: ["rw", "nosuid", "noexec", "nodev", "relatime"]
    binds:
      - /etc/resolv.conf:/etc/resolv.conf
      - /var/lib/docker:/var/lib/docker
      - /lib/modules:/lib/modules
      - /etc/docker/daemon.json:/etc/docker/daemon.json
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]

files:
  - path: etc/securetty
    contents: |
      tty0
      tty1
      ttyS0
    mode: "0644"
  - path: etc/getty.shadow
    # sample sets password for root to "abcdefgh" (without quotes)
    contents: |
      root:$6$6tPd2uhHrecCEKug$8mKfcgfwguP7f.BLdZsT1Wz7WIIJOBY1oUFHzIv9/O71M2J0EPdtFqFGTxB1UK5ejqQxRFQ.ZSG9YXR0SNsc11:17322:0:::::
  - path: var/lib/docker
    directory: true
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
    mode: "0644"
trust:
  org:
    - linuxkit
    - library
```

With 1G RAM, the login works. With 512MB, login is refused for lack of etc/securetty. 

If the service application itself (in this case getty) does not complain about the missing data (I saw errors only if containerd could not find config.json) the VM may run with the wrong configuration, therefore posing a security issue as well.

**Describe the results you expected:**

I am not directly concerned because I'm not interested in having lots of small VMs, but some might find the requirements too high.
If the behavior cannot be improved by LinuxKit, it would be useful to have a feedback, error or documentation about the issue. It would also be interesting to know if the minimum requirements depend on the size of the file system or anything else.

Most troubling is the fact that a VM can run with a different configuration depending on the VM flavor.
