### ISSUE TITLE
Investigate using LinuxKit system containerd for yml/docker.yml example via --containerd option

### ISSUE THREAD

**Issue by eyz** [linuxkit/linuxkit#2841]
**Description**

**Steps to reproduce the issue:**
**Describe the results you received:**
**Describe the results you expected:**
**Additional information you deem important (e.g. issue happens only occasionally):**
dockerd supports `--containerd`, which explicitly uses a containerd listening on the specified unix socket. Since 17.12.0-ce is out now, and containerd is well integrated, it may be time to look at using the LinuxKit system containerd for the yml/docker.yml example.

**Comment by eyz** [comment]
Pinging @justincormack, as he had mentioned this as a possibility. I gave it a try, but did not have much success getting namespaces working as intended for this, and I think a core maintainer, or perhaps k8s contributor likely could assist in this area

**Comment by justincormack** [comment]
@eyz have you got the yaml file you tried?

**Comment by eyz** [comment]
@justincormack I'm using a custom 18.01.0-dind (as of today) as well, so I can't simply provide the YAML, unfortunately. I will give it another try with the current head LinuxKit and mainline docker-ce 17.12.0 and document my findings here. Thanks!

**Comment by pwFoo** [comment]
Have you tried to mount linuxkit containerd and runc inside of your docker service as docker-containerd and docker-runc? It should work, because dockerd searching for docker-* inside of the container PATH.

I tested it some weeks ago with a custom docker image (removed containerd, runc) and it worked for me.

**Comment by eyz** [comment]
Interesting idea. Thanks. I'll try that method as some point too

**Comment by eyz** [comment]
@pwFoo do you still have notes on exactly what to bind mount in? I'm getting an error like

**Comment by pwFoo** [comment]
Quick test failed. Maybe something changed (linuxkit containerd namespace for example). It was easy like that:

1. use default docker.yml 
1. add binds
```
  - name: docker
    image: docker:17.07.0-ce-dind
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /var/lib/docker:/var/lib/docker
     - /lib/modules:/lib/modules
     - /etc/docker/daemon.json:/etc/docker/daemon.json
     - /usr/bin/runc:/usr/local/bin/docker-runc
     - /usr/bin/containerd:/usr/local/bin/docker-containerd
     - /usr/bin/containerd-shim:/usr/local/bin/docker-containerd-shim
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
```

But quick test not starting / pull image... So something may be changed in the last weeks and breaks that. Sorry

**Comment by eyz** [comment]
I'm not using Docker Engine on LinuxKit at this time, and haven't attempted this since. Should we close this, or does anyone know if this has been confirmed as working?

**Comment by justincormack** [comment]
Lets keep it open as we do want this to work eventually

**Comment by vbogretsov** [comment]
Hello!
I'm trying to use host's containerd, but getting the error when running any container:

(ns: getty) linuxkit-02500000001b:~# ctr -n services.linuxkit t exec --exec-id e1 docker docker run alpine:3.12 ping example.org
Unable to find image 'alpine:3.12' locally
3.12: Pulling from library/alpine
188c0c94c7c5: Pulling fs layer
188c0c94c7c5: Verifying Checksum
188c0c94c7c5: Download complete
188c0c94c7c5: Pull complete
Digest: sha256:c0e9560cda118f9ec63ddefb4a173a2b2a0347082d7dff7dc14272e7841a5b5a
Status: Downloaded newer image for alpine:3.12
[   63.666234] docker0: port 1(veth396a4b0) entered blocking state
[   63.667373] docker0: port 1(veth396a4b0) entered disabled state
[   63.676308] device veth396a4b0 entered promiscuous mode
[   63.809206] IPVS: ftp: loaded support on port[0] = 21
[   63.890336] docker0: port 1(veth396a4b0) entered disabled state
[   63.891548] device veth396a4b0 left promiscuous mode
[   63.892538] docker0: port 1(veth396a4b0) entered disabled state
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"fork/exec /proc/6/exe: no such file or directory\\\"\"": unknown.

my image yaml is:

```yaml
kernel:
  image: linuxkit/kernel:5.4.39
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
- linuxkit/init:a68f9fa0c1d9dbfc9c23663749a0b7ac510cbe1c
- linuxkit/runc:v0.8
- linuxkit/containerd:a4aa19c608556f7d786852557c36136255220c1f
- linuxkit/ca-certificates:v0.8
onboot:
- name: sysctl
  image: linuxkit/sysctl:v0.8
- name: sysfs
  image: linuxkit/sysfs:v0.8
- name: format
  image: linuxkit/format:v0.8
- name: mount
  image: linuxkit/mount:v0.8
  command: ["/usr/bin/mountie", "/var/lib/docker"]
- name: metadata
  image: linuxkit/metadata:v0.8
services:
- name: getty
  image: linuxkit/getty:v0.8
  env:
  - INSECURE=true
- name: rngd
  image: linuxkit/rngd:v0.8
- name: dhcpcd
  image: linuxkit/dhcpcd:v0.8
- name: ntpd
  image: linuxkit/openntpd:v0.8
- name: docker
  image: docker:19.03.14-dind
  capabilities:
  - all
  net: host
  mounts:
  - type: cgroup
    options:
    - rw
    - nosuid
    - noexec
    - nodev
    - relatime
  binds:
  - /etc/resolv.conf:/etc/resolv.conf
  - /var/lib/docker:/var/lib/docker
  - /lib/modules:/lib/modules
  - /etc/docker/daemon.json:/etc/docker/daemon.json
  - /run/docker:/var/run
  - /run/containerd/containerd.sock:/var/run/containerd/containerd.sock
  runtime:
    mkdir:
    - /run/docker
  command:
  - /usr/local/bin/docker-init
  - /usr/local/bin/dockerd
  - --
  - --containerd
  - /var/run/containerd/containerd.sock
files:
- path: var/lib/docker
  directory: true
- path: etc/docker/daemon.json
  contents: '{"debug": true}'
trust:
  org:
  - linuxkit
  - library
```

I can confirm when I don't mount containerd.sock and dockerd starts another instance of containerd a container can be run successfully.
