### ISSUE TITLE
Add support for persisted disks in rpi3

### ISSUE THREAD

**Issue by ernoaapa** [linuxkit/linuxkit#2964]
[In the documentation](https://github.com/linuxkit/linuxkit/blob/master/docs/platform-rpi3.md#disks) says:
> There currently is no support for persistent disks for the Raspberry Pi. It may be possible to partition the SD card, format a second partition as ext4 (or similar), and use it for persistent storage.
> TODO: Experiment with and document this set up.

I got interested to experiment this, mainly because you run out of memory really quickly with RPI3 (1GB RAM only), but I get stuck and I hope someone could give ideas how to get forward.

Here's my progress so far:
- Partitioned the sdcard same way as Raspberian does (1 fat32 boot partition and another ext4)
- Device boot up nicely
- But cannot see any `/dev/mmc*` devices. `lsblk` and `blkid` returns empty.
- If I run `modprobe mmc_block` it will create the block devices `/dev/mmc*` and everything starts to work as it should (can see the device, can mount it, etc.)

=> So for some reason the `mmc_block` doesn't get loaded (if that's the right one?)

There's mention in [the documentation](https://github.com/linuxkit/linuxkit/blob/master/docs/platform-rpi3.md#networking) that the network driver is not cold plugged.
If I try to use the same workaround, add following to `onboot`, it still doesn't work:
```
 - name: mmcdev
    image: linuxkit/modprobe:<hash>
    command: ["modprobe", "mmc_block"]
```

Questions what I have at the moment:
- Why calling `modprobe mmc_block` in `onboot` doesn't work, but calling it afterward after the boot through terminal work?
- Any ideas what is the issues with `mdev` and cold pluging?
- Any other ideas how to debug this?

I'm not an expert of Linux boot process, but I'm interested to dig into this and at the same time learn :)

**Comment by rn** [comment]
I haven't tried using the SD card at all yet on the RPi but your approach looks ok. I was more thinking about using a USB stick for storage.

just to make sure, your YAML file contains:
```
linuxkit/modprobe:88a819eb4c1a0a5dac4c243e6d97841ed8c725ef
```
and not literally `linuxkit/modprobe:<hash>`

I've booted the YAML below on KVM on a arm64 machine and it loaded the module just fine.
```
Module                  Size  Used by    Not tainted
mmc_block              40960  0
mmc_core              135168  1 mmc_block
```

Do you have a serial attached? Cut you provide the output?


Here is the YAML I used:
```
kernel:
  image: linuxkit/kernel:4.14.27
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:b212cfeb4bb6330e0a7547d8010fe2e8489b677a
  - linuxkit/runc:7c39a68490a12cde830e1922f171c451fb08e731
  - linuxkit/containerd:37e397ebfc6bd5d8e18695b121166ffd0cbfd9f0
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.2
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: mmcdev
    image: linuxkit/modprobe:88a819eb4c1a0a5dac4c243e6d97841ed8c725ef
    command: ["modprobe", "mmc_block"]
services:
  - name: getty
    image: linuxkit/getty:v0.2
    env:
     - INSECURE=true
trust:
  org:
    - linuxkit
```

**Comment by ernoaapa** [comment]
Thanks @rn! Tested with following YAML and it works in RPI3 (had to add the `modprobe smsc95xx` so `dhcpd` can resolve ip address):
```
kernel:
  image: linuxkit/kernel:4.14.27
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:b212cfeb4bb6330e0a7547d8010fe2e8489b677a
  - linuxkit/runc:7c39a68490a12cde830e1922f171c451fb08e731
  - linuxkit/containerd:37e397ebfc6bd5d8e18695b121166ffd0cbfd9f0
onboot:
  # https://github.com/linuxkit/linuxkit/blob/master/docs/platform-rpi3.md#networking
  - name: netdev
    image: linuxkit/modprobe:v0.2
    command: ["modprobe", "smsc95xx" ]
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.2
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: mmcdev
    image: linuxkit/modprobe:88a819eb4c1a0a5dac4c243e6d97841ed8c725ef
    command: ["modprobe", "mmc_block"]
services:
  - name: getty
    image: linuxkit/getty:v0.2
    env:
     - INSECURE=true
trust:
  org:
    - linuxkit
```

Main differences to my previous configs were:
1. `linuxkit/kernel:4.9.81` vs `linuxkit/kernel:4.14.27`
2. `linuxkit/init:d899eee3560a40aa3b4bdd67b3bb82703714b2b9` vs `linuxkit/init:b212cfeb4bb6330e0a7547d8010fe2e8489b677a`
3. Run `getty` as last step of `onboot` not as a service (for debugging)
4. Bunch of other stuff in `services` but should not be the issue

I will verify what was the root cause later when next to my rpi3. I'm betting the 3. but kind of a strange, because I have assumed that stuff in `onboot` runs in sequence so it should be loaded when it reaches the `getty` in the `onboot` execution.

Should I add this to the docs so next one doesn't need to spend time with this?

**Comment by rn** [comment]
Great to hear.

`onboot` containers do run in sequence. Most likely cause was the change of `init`.

If you have a working set up with a partitioned SD card, it would be great if you could document it and maybe add a fully working example in `./examples`.

**Comment by rn** [comment]
FWIW https://github.com/linuxkit/linuxkit/pull/3023 added support for USB storage to the kernel. So now you can/should be able to use a USB disk for external storage on a RPi3.

**Comment by sprat** [comment]
I finally found why the drivers are not automatically loaded. In fact, mdev needs to be instructed to load drivers when a device is hotplugged, so I added this section in my linuxkit YAML file:
```
files:
  - path: etc/mdev.conf
    mode: "0644"
    contents: |
      # support module loading on hotplug
      $MODALIAS=.*    root:root 660 @/sbin/modprobe "$MODALIAS"
```

Not sure why the mdev.conf file is not included by default.
No need to modprobe anymore ;)
