### ISSUE TITLE
[vmware] Is there any examples on how to mount the hgfs shared folder in fusion/workstation

### ISSUE THREAD

**Issue by weikinhuang** [linuxkit/linuxkit#2973]
**Description**

I'm trying to use linuxkit to build a replacement for boot2docker on my desktop for dev work with docker. But I can't figure out how to mount the host filesystem (via shared folders)

**Steps to reproduce the issue:**

This is the config I used based off the vmware example file

```yaml
kernel:
  image: linuxkit/kernel:4.14.29
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:7af4e32f31f04d6c63d457c502d2f69344db7d72
  - linuxkit/runc:e4b01b68b225d694a60f8b335258bd2144971239
  - linuxkit/containerd:d03b69c7d23fdae0fec1b6e62a72d362992135df
  - linuxkit/ca-certificates:04a6dc9e5c901ee128c353f690bd97aeb7d97ae8
onboot:
  - name: sysctl
    image: linuxkit/sysctl:e7106b5e3db64a9ec21eb1479727627ecf52137d
  - name: sysfs
    image: linuxkit/sysfs:f7fc4dfbdc7e09f8aab0063699d9a75932b08c3f
  - name: open-vm-tools
    image: linuxkit/open-vm-tools:fd0b0bc2c57da0ed069a423fb5a3494499fb1ac0
    command: ["/usr/bin/vmhgfs-fuse", "-o", "allow_other", ".host:/", "/mnt/hgfs"]
    capabilities:
      - all
    binds:
      - /lib/modules:/lib/modules
      - /mnt:/mnt:rbind,rshared
services:
  - name: getty
    image: linuxkit/getty:9e2c184fdd708720d47e663f03ad137c074d4f21
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:8bcfb9a90470161a04f25e58407852a3d1ad499a
  - name: dhcpcd
    image: linuxkit/dhcpcd:8b23f047ffa4d657a2c7dd465e69cc13721c4165
  - name: ntpd
    image: linuxkit/openntpd:e3cd26ff2974f2d93c88c28efacf69e15bcdb983
  - name: open-vm-tools
    image: linuxkit/open-vm-tools:fd0b0bc2c57da0ed069a423fb5a3494499fb1ac0
    binds:
      - /lib/modules:/lib/modules
      - /mnt:/mnt:rbind,rshared
    capabilities:
      - CAP_SYS_ADMIN
    rootfsPropagation: shared
  - name: sshd
    image: linuxkit/sshd:b24724013759bbcb084600d1157735ccfc9aa615
  - name: nginx
    image: nginx:1.13.8-alpine
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
files:
  - path: mnt/hgfs
    directory: true
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
trust:
  org:
    - linuxkit
    - library
```

After the vm boots up, I manually add a shared folder.

SSH into the vm:

```bash
ctr --namespace services.linuxkit t exec -t --exec-id vmware-$(uuidgen) open-vm-tools sh

/ # cd /mnt/
/mnt # ls -la
total 0
drwxr-xr-x    2 root     root            40 Mar 28 17:32 .
drwxr-xr-x    1 root     root           120 Mar 28 17:32 ..

/mnt # mkdir -p /mnt/hgfs
mkdir: can't create directory '/mnt/hgfs': Read-only file system

/mnt # vmhgfs-fuse -o allow_other .host:/ /mnt
fuse: device not found, try 'modprobe fuse' first

/mnt # ls -al /lib/modules/
total 0
drwxr-xr-x    3 root     root            60 Mar 28 17:32 .
drwxr-xr-x    1 root     root            60 Mar 28 17:32 ..
drwxr-xr-x    4 root     root           320 Mar 28 17:32 4.14.29-linuxkit

/mnt # find /lib/modules/4.14.29-linuxkit/ -iname '*fuse*'
-- No files found
```

**Describe the results you received:**

There are no mounted folder in `/mnt/hgfs`

**Describe the results you expected:**

Expected `/mnt/hgfs` to be available.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by rn** [comment]
I don't know how `hgfs` is implemented, but the fuse filesystem is compiled into the kernel, ie not as a module, see for example: https://github.com/linuxkit/linuxkit/blob/master/kernel/config-4.14.x-x86_64#L3380

Also, keep in mind that your ssh connection is into a container and therefore is namespaced.

**Comment by weikinhuang** [comment]
@rn 

I managed to get the mount running within the open-vm-tools process, but unable to get it to run on boot and unable to share the mount to other processes (IE if I wanted to run `docker` with mounting `/mnt:/mnt`).

If I ssh into the vm and exec into the `open-vm-tools` container:

```bash
(ns: sshd) linuxkit-000c29432143:~# ctr --namespace services.linuxkit t exec -t --exec-id vmware-$(uuidgen) open-vm-tools sh

/ # vmhgfs-fuse -o allow_other .host:/ /mnt

/ # ls -la /mnt
total 9
dr-xr-xr-x    1 root     root          4192 Mar 29 01:26 .
drwxr-xr-x    1 root     root           120 Mar 28 21:20 ..
drwxrwxrwx    1 root     root          4096 Mar 29 01:20 linuxkit-test

```

I am also unable to create the `/mnt/hgfs` directory on the root fs using:

```yaml
files:
  - path: mnt/hgfs
    directory: true
```

My current configuration is as follows:

```yaml
kernel:
  image: linuxkit/kernel:4.14.29
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:7af4e32f31f04d6c63d457c502d2f69344db7d72
  - linuxkit/runc:e4b01b68b225d694a60f8b335258bd2144971239
  - linuxkit/containerd:d03b69c7d23fdae0fec1b6e62a72d362992135df
  - linuxkit/ca-certificates:04a6dc9e5c901ee128c353f690bd97aeb7d97ae8
onboot:
  - name: sysctl
    image: linuxkit/sysctl:e7106b5e3db64a9ec21eb1479727627ecf52137d
  - name: sysfs
    image: linuxkit/sysfs:f7fc4dfbdc7e09f8aab0063699d9a75932b08c3f
  - name: open-vm-tools
    image: linuxkit/open-vm-tools:fd0b0bc2c57da0ed069a423fb5a3494499fb1ac0
    command: ["mknod", "-m", "666", "/dev/fuse", "c", "10", "229"]
    net: host
    capabilities:
      - all
    binds:
      - /lib/modules:/lib/modules
      - /dev:/dev
  - name: open-vm-tools
    image: linuxkit/open-vm-tools:fd0b0bc2c57da0ed069a423fb5a3494499fb1ac0
    command: ["mkdir", "-p", "/mnt/hgfs"]
    binds:
      - /mnt:/mnt
  - name: open-vm-tools
    image: linuxkit/open-vm-tools:fd0b0bc2c57da0ed069a423fb5a3494499fb1ac0
    command: ["/usr/bin/vmhgfs-fuse", "-o", "allow_other", ".host:/", "/mnt/hgfs"]
    net: host
    capabilities:
      - all
    binds:
      - /lib/modules:/lib/modules
      - /dev:/dev
      - /mnt:/mnt
services:
  - name: getty
    image: linuxkit/getty:9e2c184fdd708720d47e663f03ad137c074d4f21
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:8bcfb9a90470161a04f25e58407852a3d1ad499a
  - name: dhcpcd
    image: linuxkit/dhcpcd:8b23f047ffa4d657a2c7dd465e69cc13721c4165
  - name: ntpd
    image: linuxkit/openntpd:e3cd26ff2974f2d93c88c28efacf69e15bcdb983
  - name: open-vm-tools
    image: linuxkit/open-vm-tools:fd0b0bc2c57da0ed069a423fb5a3494499fb1ac0
    net: host
    binds:
      - /lib/modules:/lib/modules
      - /dev:/dev
      - /mnt:/mnt
    capabilities:
      - all
  - name: sshd
    image: linuxkit/sshd:b24724013759bbcb084600d1157735ccfc9aa615
files:
  - path: /mnt/hgfs
    directory: true
  - path: /root/.ssh/authorized_keys
    source: ./id_rsa.pub
    mode: "0600"
    optional: true
trust:
  org:
    - linuxkit
    - library
```

**Comment by tjfontaine** [comment]
Here's my example, then in subsequent services in you can have binds that are `/var/lib/hgfs/<sharename>:/path/in/container`

```yaml
kernel:
  image: linuxkit/kernel:4.14.79
  cmdline: "console=tty0 page_poison=1"
init:
  - linuxkit/init:c563953a2277eb73a89d89f70e4b6dcdcfebc2d1
  - linuxkit/runc:83d0edb4552b1a5df1f0976f05f442829eac38fe
  - linuxkit/containerd:326b096cd5fbab0f864e52721d036cade67599d6
  - linuxkit/ca-certificates:v0.6
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.6
  - name: sysfs
    image: linuxkit/sysfs:v0.6
  - name: binfmt
    image: linuxkit/binfmt:v0.6
  # Format and mount the disk image in /var/lib/docker
  - name: format
    image: linuxkit/format:v0.6
  - name: mount
    image: linuxkit/mount:v0.6
    command: ["/usr/bin/mountie", "/var/lib"]
  - name: mkdir-hgfs
    image: linuxkit/open-vm-tools:v0.6
    command: ["mkdir", "-p", "/var/lib/hgfs"]
    binds:
      - /var/lib:/var/lib
  - name: mount-fuse
    image: linuxkit/open-vm-tools:v0.6
    command: ["/usr/bin/vmhgfs-fuse", "-o", "allow_other", ".host:/", "/var/lib/hgfs"]
    rootfsPropagation: shared
    capabilities:
      - all
    binds:
      - /lib/modules:/lib/modules
      - /dev:/dev
      - /var/lib:/var/lib:rbind,rshared
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.6
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  # Enable acpi to shutdown on power events
  - name: acpid
    image: linuxkit/acpid:v0.6
  # Enable getty for easier debugging
  - name: getty
    image: linuxkit/getty:2eb742cd7a68e14cf50577c02f30147bc406e478
    env:
        - INSECURE=true
  - name: open-vm-tools
    image: linuxkit/open-vm-tools:v0.6
trust:
    org:
        - linuxkit
        - library
```
