### ISSUE TITLE
Unable to join swarm in AWS with build that works locally on HyperKit

### ISSUE THREAD

**Issue by dweomer** [linuxkit/linuxkit#3028]
**Description**
I have built a linuxkit image that is an amalgam of the `examples/aws.yml` and the `examples/docker.yml` for the purpose of experimenting with various Swarm configurations. With the 4.14 kernel, however, I am having problems joining more than one manager to the swarm. I can join workers and deploy services without problem, executing `docker swarm join` with the manager token OR `docker node promote` from the leader result in session timeouts in the logs and the leader giving up leadership.

When attempting to join a new manager I get a hang of 10-15 seconds, but no error message -- it appears to have joined. But, taking a look at the `docker node ls` output:
```
ip-172-30-0-21:/# docker node ls
ID                            HOSTNAME                                    STATUS              AVAILABILITY        MANAGER STATUS
z2qydmywbs6161nw0j3zitwm6 *                                               Unknown             Active              Unreachable
22e0jzf30oyo700uzrn9nqaw7     ip-172-30-0-39.us-west-2.compute.internal   Ready               Active              Reachable
ip-172-30-0-21:/#
```

... invariably the node that I joined from is unreachable from **itself**.

After attempting various versions of Docker and turning of IPv6 (via the `sysctl` onboot) I was not able to get multiple managers to join a swarm until I downgraded the kernel to 4.9.x. Not sure what is going on here and maybe this report is more appropriate for the moby or swarmkit repos. I am open to suggestions.

**Steps to reproduce the issue:**

Build the LinuxKit image for AWS from the below YAML and deploy to AWS. Then push to AWS and deploy 2-3 instances. Execute `docker swarm init` on the first instance and then `docker swarm join-token manager` to emit the command to run on the remaining manager instances. Execute the `docker swarm join` command emitted for the manager token on another instance. It will hang a bit longer than normal but then return fine. Invoking `docker node ls` on the node you attempted to join from will result in auto-unreachability.

```
kernel:
  image: linuxkit/kernel:4.14.38
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:11929b0007b87384f7372e9265067479c4616586
  - linuxkit/runc:acba8886e4b1318457c711700f695a02fef9493d
  - linuxkit/containerd:f197e7cbb2ede4370b75127c76de6f7b2e3d9873
  - linuxkit/ca-certificates:fb5c7bf842a330f5b47cdf71f950fe0c85f4a772
onboot:
  - name: sysctl
    image: linuxkit/sysctl:b51c3da02bc2fc9a53f699efc51f650ac17ffac8
  - name: sysfs
    image: linuxkit/sysfs:98b340d360541f1e1e62bc30b62ab6a7e3dc9280
  - name: dhcpcd
    image: linuxkit/dhcpcd:01069780f536da8eb7745df7478a97253403b63d
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:be507a0718df8ed6733dfab1d6866672f446e8fd
  - name: format
    image: linuxkit/format:d24885a226c42a40f7ed44dd3789a6a035254d98
  - name: mount
    image: linuxkit/mount:763e67d733342281f3bdc55d7208b9c442837afe
    command: ["/usr/bin/mountie", "/var/lib/docker"]
services:
  - name: getty
    image: linuxkit/getty:b286a610ccbebc45251f3a9df3619d76318e2244
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:429e1308b8cad9dbe04b7a91fcebec17ee6f7591
  - name: ntpd
    image: linuxkit/openntpd:9851e80f16e4292b12fbe97b9d7f1c3dd40d1ea2
  - name: sshd
    image: linuxkit/sshd:8f11ee09b101ab7f41c7a6409a8d7a8d49957fbb
    binds:
     - /run/config/ssh/authorized_keys:/root/.ssh/authorized_keys
  - name: docker
    image: docker:17.09.0-ce-dind
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /var/lib/docker:/var/lib/docker
     - /lib/modules:/lib/modules
     - /etc/docker/daemon.json:/etc/docker/daemon.json
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
files:
  - path: var/lib/docker
    directory: true
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
trust:
  org:
    - linuxkit
    - library
```

**Describe the results you received:**

Unable to create HA Swarm in AWS.

**Describe the results you expected:**

Ability to create HA Swarm in AWS.

**Additional information you deem important (e.g. issue happens only occasionally):**

I will respond to this with logs from the `swarm init` and `swarm join` managers.
