### ISSUE TITLE
linuxkit build cannot encode header

### ISSUE THREAD

**Issue by Gabology** [linuxkit/linuxkit#3091]
**Description**
Running `linuxkit build` with the `docker.elastic.co/logstash/logstash-oss` repository fails.

**Steps to reproduce the issue:**
YAML file
```yml
kernel:
  image: linuxkit/kernel:4.14.52
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:0e4af96fecc8f752c80d41c0b7d06570cc1dc6b2
  - linuxkit/runc:v0.4
  - linuxkit/containerd:27a4c84cc8fab2d5ea04342546ecd20453ec99b3
  - linuxkit/ca-certificates:v0.4
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.4
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.4
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:v0.4
services:
  - name: getty
    image: linuxkit/getty:44730fd0a7c59dbacf5b48b54ba33f551bcf7ef0
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:v0.4
  - name: logstash
    image: "docker.elastic.co/logstash/logstash-oss:6.3.0"
    binds:
      - /etc/resolv.conf:/etc/resolv.conf
      - /run/config/logstash/config:/usr/share/logstash/config
      - /run/config/logstash/pipeline:/usr/share/logstash/pipeline
trust:
  org:
    - linuxkit
    - library
```

`linuxkit build -format iso-efi logstash.yml`

**Describe the results you received:**
```
Extract kernel image: linuxkit/kernel:4.14.52
Add init containers:
Process init image: linuxkit/init:0e4af96fecc8f752c80d41c0b7d06570cc1dc6b2
Process init image: linuxkit/runc:v0.4
Process init image: linuxkit/containerd:27a4c84cc8fab2d5ea04342546ecd20453ec99b3
Process init image: linuxkit/ca-certificates:v0.4
Add onboot containers:
  Create OCI config for linuxkit/sysctl:v0.4
  Create OCI config for linuxkit/dhcpcd:v0.4
  Create OCI config for linuxkit/metadata:v0.4
Add service containers:
  Create OCI config for linuxkit/getty:44730fd0a7c59dbacf5b48b54ba33f551bcf7ef0
  Create OCI config for linuxkit/rngd:v0.4
  Create OCI config for docker.elastic.co/logstash/logstash-oss:6.3.0
FATA[0022] Failed to extract root filesystem for docker.elastic.co/logstash/logstash-oss:6.3.0: archive/tar: cannot encode header: Format specifies USTAR; and USTAR cannot encode Linkname="containers/services/logstash/lower/usr/lib/python2.7/site-packages/kitchen/collections/strictdict.pyc"
```

**Describe the results you expected:**
That the image would build successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**
OSX 10.13.5, docker version 18.03.1-ce
