### ISSUE TITLE
Command validation

### ISSUE THREAD

**Issue by scriptjs** [linuxkit/linuxkit#3110]
**Description**
Commands are not being validated properly. Improperly quoted list items validate, enabling the creation of an image. This can lead to services failing when running the image without reporting that could have identified the issue in the build phase.

**Steps to reproduce the issue:**
Build the following image. ie `linuxkit build -format vmdk docker.yml`. Notice the improperly quoted command `command: ["/usr/bin/mountie", /var/lib/docker"]`.

```
kernel:
  image: linuxkit/kernel:4.14.54
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:v0.5
  - linuxkit/runc:v0.5
  - linuxkit/containerd:v0.5
  - linuxkit/ca-certificates:v0.5
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.5
  - name: sysfs
    image: linuxkit/sysfs:v0.5
  - name: format
    image: linuxkit/format:v0.5
  - name: mount
    image: linuxkit/mount:v0.5
    command: ["/usr/bin/mountie", /var/lib/docker"]
services:
  - name: getty
    image: linuxkit/getty:v0.5
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:v0.5
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.5
  - name: ntpd
    image: linuxkit/openntpd:v0.5
  - name: docker
    image: docker:18.05.0-ce-dind
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /var/lib/docker:/var/lib/docker
     - /lib/modules:/lib/modules
     - /etc/docker/daemon.json:/etc/docker/daemon.json
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
files:
  - path: var/lib/docker
    directory: true
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
trust:
  org:
    - linuxkit
    - library
```

**Describe the results you received:**
The build will succeed without a fatal validation error. This enables running the image where Docker fails without knowledge of the error.

**Describe the results you expected:**
A validation error should be thrown upon execution of `linuxkit build`

**Additional information you deem important (e.g. issue happens only occasionally):**
Question: Is YAML the best choice of language for LinuxKit configuration. JSON is noisy relative to YAML but could provide validation support.

**Comment by justincormack** [comment]
You can already use JSON (as it is accepted), and you can validate it with the existing JSON schema, which is here https://github.com/moby/tool/blob/master/src/moby/schema.go

**Comment by scriptjs** [comment]
Hi Justin. Thank you for pointing this out. I will use it. So I am assuming had used moby tool instead of linuxkit, the above schema have caught the error. Is that correct?

**Comment by ijc** [comment]
FWIW the `containers/onboot/003-mount/config.json` resulting from the above contains:
 ```
        "args": [
            "/usr/bin/mountie",
            "/var/lib/docker\""
        ],
```
I think `linuxkit build` also validates the schema in the exact same was so switching to `moby build` instead wouldn't make a difference.

I hadn't realised the YAML rules around quoting were so... subtle... as to parse `foo"` into `"foo\""`

**Comment by justincormack** [comment]
The yaml rules around quoting are really horrible actually... one of the worst things.

**Comment by ijc** [comment]
No kidding!

Just for completeness I added a
```
  - path: etc/linuxkit-config
    metadata: yaml
```
to the `files` section and the result has (as, now, expected):
```
- name: mount
  image: docker.io/linuxkit/mount:v0.5@sha256:6147c2815e24dfb65ef785bf987f2f7c13e93f3c60473f0f66d476b77143f375
  command:
  - /usr/bin/mountie
  - /var/lib/docker"
```
