### ISSUE TITLE
Unable to connect to sshd on GCP

### ISSUE THREAD

**Issue by steeve** [linuxkit/linuxkit#3118]
**Description**

Trying to ssh on a linuxkit on GCP results in a `connection refused`.

**Steps to reproduce the issue:**

Using the following `yml` on GCP:
```
kernel:
  image: linuxkit/kernel:4.14.55
  cmdline: "console=ttyS0"
init:
  - linuxkit/init:3f1e5c32d6ca9e83a7ea7ad9854da2032971a83f
  - linuxkit/runc:v0.5
  - linuxkit/containerd:v0.5
  - linuxkit/ca-certificates:v0.5
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.5
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.5
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: linuxkit/getty:v0.5
    env:
      - INSECURE=true
  - name: acpid
    image: linuxkit/acpid:v0.5
  - name: rngd
    image: linuxkit/rngd:v0.5
  - name: ntpd
    image: linuxkit/openntpd:v0.5
  - name: sshd
    image: linuxkit/sshd:v0.5
    binds:
      - /root/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro
files:
  - path: etc/linuxkit-config
    metadata: yaml
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
trust:
  org:
    - linuxkit
    - library
```

**Describe the results you received:**

Got a connection refused:
```
$ gcloud compute ssh linuxkit
ssh: connect to host xx.xx.xx.xx port 22: Connection refused
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
```

Even using `nc` from another instance results in the same issue.

The same yml works fine with run on `hyperkit` and `vmnet`.

**Describe the results you expected:**

Successfully connect.
