### ISSUE TITLE
cannot boot from usb iso image on bare metal 

### ISSUE THREAD

**Issue by logicminds** [linuxkit/linuxkit#3154]
**Description**
The computer that is booting off the usb drive is unable to mount the root filesystem during the boot sequence

**Steps to reproduce the issue:**
1. git clone github.com/linuxkit
2. cd linuxkit/examples
3. mkdir wireguard && mv wireguard.yml wireguard/
4. linuxkit build --format iso-bios wireguard.yml
5. Insert 16 GB usb flash drive into computer
6. sudo dd if=wireguard.iso of=/dev/rdisk2 bs=1m
7. Take out flash drive when complete
8. Put flash drive into motherboard or computer capable of booting from usb drive
9. Power on and watch boot sequence

**Describe the results you received:**
Kernel panic  - not syncing - VFS: Unable to mount root fs, unknown block(0,0)

**Describe the results you expected:**
I expected to see the text below during the boot.
```
    1.740835] Freeing unused kernel memory: 1512K
[    1.763587] Write protecting the kernel read-only data: 18432k
[    1.763587] Write protecting the kernel read-only data: 18432k
[    1.765206] Freeing unused kernel memory: 2024K
[    1.765206] Freeing unused kernel memory: 2024K
[    1.768204] Freeing unused kernel memory: 1100K
[    1.768204] Freeing unused kernel memory: 1100K

Welcome to LinuxKit

                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
          {                       /  ===-
           \______ O           __/
             \    \         __/
              \____\_______/

[    2.346960] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[    2.346960] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[    2.552594] clocksource: Switched to clocksource tsc
[    2.552594] clocksource: Switched to clocksource tsc
[    2.723036] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[    2.723036] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Works fine when booting from hyperkit and virtual machine (vmware fusion).  Just not  bare metal.

Bare metal machine boots from other live images without issue.

The usb drive is the only storage device in the system.

## Wireguard Config
```
kernel:
  image: linuxkit/kernel:4.14.58
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:v0.6
  - linuxkit/runc:v0.6
  - linuxkit/containerd:v0.6
  - linuxkit/ca-certificates:v0.6
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.6
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.6
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: wg0
    image: linuxkit/ip:v0.6
    net: new
    binds:
      - /etc/wireguard:/etc/wireguard
    command: ["/usr/bin/lk-wg-config", "configure", "/etc/wireguard/wg0.conf"]
    runtime:
      interfaces:
        - name: wg0
          add: wireguard
          createInRoot: true
      bindNS:
          net: /run/netns/wg0
  - name: wg1
    image: linuxkit/ip:v0.6
    net: new
    binds:
      - /etc/wireguard:/etc/wireguard
    command: ["/usr/bin/lk-wg-config", "configure", "/etc/wireguard/wg1.conf"]
    runtime:
      interfaces:
        - name: wg1
          add: wireguard
          createInRoot: true
      bindNS:
          net: /run/netns/wg1
services:
  - name: getty
    image: linuxkit/getty:v0.6
    env:
     - INSECURE=true
    net: /run/netns/wg1
  - name: rngd
    image: linuxkit/rngd:v0.6
  - name: nginx
    image: nginx:1.13.8-alpine
    net: /run/netns/wg0
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
files:
  - path: etc/wireguard/wg0.conf
    contents: |
      [Interface]
      Address = 192.168.2.1/24
      DNS = 192.168.2.2
      PrivateKey = KG7EKkHDkp7THfW5mOXcZzo3RbGAjq+ARMfJGFm5G1s=
      ListenPort = 51820
      [Peer]
      PublicKey = ZP7h1OjA1oIAmsAvMKujp2RAAC/f0kY814b3Xq6j/0Y=
      AllowedIPs = 0.0.0.0/0
      Endpoint = 127.0.0.1:51821
  - path: etc/wireguard/wg1.conf
    contents: |
      [Interface]
      Address = 192.168.2.2/24
      PrivateKey = SCGCKDuTm4PMOw+LXdK/2s8mxnv145QHOohKRq3vc2A=
      ListenPort = 51821
      [Peer]
      PublicKey = AcS5t3PC5nL/oj0sYhc3yFpDlRaXoJ0mfEq6iq0rFF4=
      AllowedIPs = 0.0.0.0/0
      Endpoint = 127.0.0.1:51820
trust:
  org:
    - linuxkit
    - library
```
