### ISSUE TITLE
Run LinuxKit in Hyper-V nested in Windows 10 VMware

### ISSUE THREAD

**Issue by StefanScherer** [linuxkit/linuxkit#3209]
**Description**

I try to use VMware Fusion on a Mac to showcase Docker Desktop in a Windows 10 VM. The VMware VM has nested virtualization turned on. I'm aware of the problems running it nested in VMware https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-for-windows-in-nested-virtualization-scenarios.

I tried Docker for Windows Edge and it does not start and the log.txt can be found in this gist https://gist.github.com/StefanScherer/f313e5b9e72196ce07f89955abd0465d#file-docker-for-win-log-txt

The MobyLinuxVM seems to hang at "Calibrating delay loop...":

```
[05:54:11.678][Moby           ][Info   ] [    0.000000] allocated 4194304 bytes of page_ext
[05:54:11.693][Moby           ][Info   ] [    0.000000] tsc: Unable to calibrate against PIT
[05:54:11.693][Moby           ][Info   ] [    0.000000] tsc: HPET/PMTIMER calibration failed
...
[05:56:13.865][Moby           ][Info   ] [    0.000000] Calibrating delay loop...
```

I then tried to use a simpler setup to reproduce the problem in the same Windows 10 VM with LinuxKit.
I have build several LinuxKit UEFI ISO's with different kernel versions. I had to build LinuxKit ISO on the Mac as linuxkit.exe depends on Linux Containers that cannot be used in the Windows 10 VM.

**Steps to reproduce the issue:**

- Create a LinuxKit EFI bootable ISO with `linuxkit build -format iso-efi linuxkit.yml` - adjust the kernel image to eg. `linuxkit/kernel:4.9.125`
- Spin up Windows 10 VM running in VMware Workstation / Fusion (or maybe vSphere, vCloud, ...) with nested hypervisor turned on. Give the VM at least 5 GB RAM.
- Install Hyper-V and `linuxkit.exe`
- Copy the linxukit-efi.iso from host into the Windows 10 VM
- Open admin powershell terminal and run `linuxkit.exe run -disk size=1 linuxkit-efi.iso`

**Describe the results you received:**

The 4.9 kernels hang in that nested environment, newer Linux kernels work fine.

- 🛑 4.9.125 hangs (the kernel used in D4Win 2.0.0.0 beta)
- 🛑 4.9.133 hangs -> [linuxkit output](https://gist.github.com/StefanScherer/f313e5b9e72196ce07f89955abd0465d#file-linuxkit-efi-4-9-133-iso-txt)
- ✅ 4.14.74 works (default linuxkit.yml from this repo)
- ✅ 4.14.76 works -> [linuxkit output](https://gist.github.com/StefanScherer/f313e5b9e72196ce07f89955abd0465d#file-linuxkit-efi-4-14-76-iso-txt)
- ✅ 4.18.15 works -> [linuxkit output](https://gist.github.com/StefanScherer/f313e5b9e72196ce07f89955abd0465d#file-linuxkit-efi-4-18-15-iso-txt)

**Describe the results you expected:**

Docker 4 Windows should work in nested environments.
Some Captains and MVP's struggle demoing Docker Desktop at meetups from their clean Mac + VMware Fusion / Windows 10 + VMware Workstation notebooks.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by rn** [comment]
Thanks for the detailed report. The calibration code itself does not seem to have changed since 3.11 but it looks a different path is take on 4.14.x than on 4.9.x

Is the hang consistent or happens sometime but not other times. IIRC when we used ESXi for CI we had temporal failures so it's worth repeating the above a few times, maybe even with different loads on the host.

**Comment by StefanScherer** [comment]
I tried it in the last few months a couple of times, always with the latest Windows 10 updates available. The Win10 VM isn't busy with other things (I normally "debloat" it by turning off Windows Defender, Windows Updates to stop Windows from draining my Mac battery), also my Mac only ran this single VM.

The hang seems reproducible, I never got D4Win running with the last versions.
Also with LinuxKit it always just stops at that message "Calibrating delay loop...".

Do you mean I should try the 4.14/4.18 with some CPU load on the Win10 to see if it still boots?

**Comment by rn** [comment]
Hmm, I've seen some nested virt systems on the `for-win` which always hung, pretty much for all through the past couple of years, so I'm a little suspicious regarding it being sensitive to the kernel version. Did it every worked for you? I used to have a pretty up-to-date windows insider VM on my iMac with VMware and it tended to work (haven't tried in quite a while). I thought it might be timing related when other folks saw it.

The 4.14.x message seems to suggest that different code path is take. Take a look at:
https://github.com/torvalds/linux/blob/master/init/calibrate.c#L275
on the 4.14 kernel `lpj_fine` seems to be set. This is likely done in arch/x86/kernel/tsc.c which has seen quite a few changes. I don't think we have the time to triage this in detail...but there were some plans to move the Docker Desktop kernel to 4.14.x at some point. But that is not that straight forward because the Hyper-V socket interface has changed completely.

There is also the `tsc` kernel command line option. You could try setting this to either `tsc=reliable` or `tsc=unstable` which might help.

**Comment by StefanScherer** [comment]
During the private beta it didn't work in VMware. After first release it worked, but not always. Since then I moved to a Windows Server 2016 VM to run Windows containers without Hyper-V on my Mac. But sometimes I had to demo D4Win so it always was a challenge.

Thanks for the details about tsc.
The kernel 4.14 somehow calculates lpj before running into that calibrate function.

```
[    0.000000] Hyper-V: Using ext hypercalls for IPI
[    0.000000] Hyper-V: Using MSR based APIC access
[    0.000000] clocksource: hyperv_clocksource_tsc_page: mask: 0xffffffffffffffff max_cycles: 0x24e6a1710, max_idle_ns: 440795202120 ns
[    0.000000] tsc: Detected 2207.885 MHz processor
[    0.000037] Calibrating delay loop (skipped), value calculated using timer frequency.. 4415.77 BogoMIPS (lpj=2207885)
```

I tried the tsc parameter and lpj parameter with kernel 4.9.x:

- 🛑 linuxkit/kernel:4.9.133 and `tsc=reliable`
- 🛑 linuxkit/kernel:4.9.133 and `tsc=unstable`
- ✅ linuxkit/kernel:4.9.133 and `lpj=2207885` -> [LinuxKit output](https://gist.github.com/StefanScherer/f313e5b9e72196ce07f89955abd0465d#file-linux-4-9-lpj-txt)

I have changed the `linuxkit.yml` like this:

```yaml
kernel:
  image: linuxkit/kernel:4.9.133
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 lpj=2207885"
...
```

And LinuxKit now boots without a problem in the nested Win10 VM.

**Comment by StefanScherer** [comment]
During the private beta it didn't work in VMware. After first release it worked, but not always. Since then I moved to a Windows Server 2016 VM to run Windows containers without Hyper-V on my Mac. But sometimes I had to demo D4Win so it always was a challenge.

Thanks for the details about tsc.
The kernel 4.14 somehow calculates lpj before running into that calibrate function.

```
[    0.000000] Hyper-V: Using ext hypercalls for IPI
[    0.000000] Hyper-V: Using MSR based APIC access
[    0.000000] clocksource: hyperv_clocksource_tsc_page: mask: 0xffffffffffffffff max_cycles: 0x24e6a1710, max_idle_ns: 440795202120 ns
[    0.000000] tsc: Detected 2207.885 MHz processor
[    0.000037] Calibrating delay loop (skipped), value calculated using timer frequency.. 4415.77 BogoMIPS (lpj=2207885)
```

I tried the tsc parameter and lpj parameter with kernel 4.9.x:

- 🛑 linuxkit/kernel:4.9.133 and `tsc=reliable`
- 🛑 linuxkit/kernel:4.9.133 and `tsc=unstable`
- ✅ linuxkit/kernel:4.9.133 and `lpj=2207885` -> [LinuxKit output](https://gist.github.com/StefanScherer/f313e5b9e72196ce07f89955abd0465d#file-linux-4-9-lpj-txt)

I have changed the `linuxkit.yml` like this:

```yaml
kernel:
  image: linuxkit/kernel:4.9.133
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 lpj=2207885"
...
```

And LinuxKit now boots without a problem in the nested Win10 VM.

**Comment by StefanScherer** [comment]
(Hm, seems like GitHub has some hiccup. I'll answer again. Just in case it shows up twice.)

Thanks for the details about the calibration and tsc parameter.

I have tried tsc parameter, but it also hangs at `Calibrating delay loop...`. Kernel 4.14 seems to calculate lpj before calling the calibration function

```
[    0.000000] tsc: Detected 2207.885 MHz processor
[    0.000037] Calibrating delay loop (skipped), value calculated using timer frequency.. 4415.77 BogoMIPS (lpj=2207885)
```

Manually setting `lpj` boots LinuxKit with kernel 4.9 as well:

- 🛑 kernel 4.9.133 + `tsc=reliable`
- 🛑 kernel 4.9.133 + `tsc=unstable`
- ✅ kernel 4.9 + `lpj=2207885` -> [LinuxKit output](https://gist.github.com/StefanScherer/f313e5b9e72196ce07f89955abd0465d#file-linux-4-9-lpj-txt)

My `linuxkit.yml` looks like this:

```yaml
kernel:
  image: linuxkit/kernel:4.9.133
  # cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 lpj=2207885"
init:
  - linuxkit/init:6eb0158059b056a1567236280880cb87f03ff008
  - linuxkit/runc:6cf26a0403376de3b5396cb676b88eea4f37aff8
  - linuxkit/containerd:d955db7cd28dbd7be8a17d7063cc6b7f1bf91f0a
  - linuxkit/ca-certificates:v0.6
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.6
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.6
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
onshutdown:
  - name: shutdown
    image: busybox:latest
    command: ["/bin/echo", "so long and thanks for all the fish"]
services:
  - name: getty
    image: linuxkit/getty:v0.6
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:v0.6
  - name: nginx
    image: nginx:1.13.8-alpine
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
files:
  - path: etc/linuxkit-config
    metadata: yaml
trust:
  org:
    - linuxkit
    - library
```
