### ISSUE TITLE
Kernel panic with simple Python Alpine base image

### ISSUE THREAD

**Issue by mattdodge** [linuxkit/linuxkit#3264]
**Description**

I'm seeing a kernel panic when trying to use a custom built package off of a relatively straightforward Alpine-based Dockerfile.

I have attached the full build and run log in [this gist](https://gist.github.com/mattdodge/565549e05c31a72f56815f5475eba1d9):
 * built with `linuxkit pkg build --disable-content-trust badpackage`
 * run with `linuxkit run badpackage`

But basically, I'm seeing this kernel panic:
```
---[ end Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
```
when including this Dockerfile:
```Dockerfile
FROM python:3.5-alpine3.7
RUN apk update \
	&& apk add --virtual build-dependencies build-base git openssl-dev
CMD ["python3", "-c", "print('Python is working!')"]
```
Here is my image yml
```yml
kernel:
  image: linuxkit/kernel:4.14.91
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:e0dced91adbfba34c53cd673760e011f410638ff
  - linuxkit/runc:b87c49e73eb14ba73d23eabf75423e987a043209
  - linuxkit/containerd:cf158d5f56c5b4867f29f0fc3ec49ea505e99333
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.6
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: linuxkit/getty:2eb742cd7a68e14cf50577c02f30147bc406e478
    env:
     - INSECURE=true
  - name: nio
    image: badpackage:1e5cdb61885de25db168997813be3b2df4655f30-dirty-amd64
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
    net: host
trust:
  org:
    - linuxkit
    - library
```

**Additional information you deem important (e.g. issue happens only occasionally):**
I was trying to pin it down to one of the apk dependencies but it seems inconsistent. For example, if you remove `git` or `build-base` from the above dependencies it works, but then adding other packages cause it to fail again.

I'm aware this may not be an issue with linuxkit, I admittedly have very little idea what I'm doing, just getting started with this. But I was hoping to get some guidance and maybe pointed to the right place to report something like this. 

Thanks very much!
