### ISSUE TITLE
Add support for Xen Hypervisors - XCP-ng / Xen Server

### ISSUE THREAD

**Issue by jmccoy555** [linuxkit/linuxkit#3312]
Xen tools package and linuxkit run backend.

I presume this should be possible, its just not implemented as no one has attempted / required it?

**Comment by rn** [comment]
I'm not aware of anyone working on this. Patches are always welcome

**Comment by deitch** [comment]
Actually, the Zededa team has been working on it, have it working as far as I know. See [this repo](https://github.com/zededa/zenbuild/), specifically [this path](https://github.com/zededa/zenbuild/tree/master/pkg/xen) and [this path](https://github.com/zededa/zenbuild/tree/master/pkg/xen-tools)

It is a little difficult to build the entire thing right now - there are some closed-source dependencies - but those packages themselves should be buildable. There is definite interest in upstreaming the work done there to mainstream linuxkit. Check back in a few weeks...

**Comment by rn** [comment]
My view is that `linuxkit run` is mostly for testing. If this is too hard to integrate for a given virtualisation solution I would prefer not to have it. Being able to build images for various virtualisation solution is more important but I suspect Xen already supports a bunch of the formats linuxkit supports

**Comment by jmccoy555** [comment]
Running from an iso works fine, just really need xen-tools.

**Comment by jmccoy555** [comment]
So I cloned the git @deitch liked to, went into the xen-tools folder and built the image, which appears to have worked. 

Then I added the service in my yml referencing the image I built, but no joy. An extra error line shows up during boot - 

> ERRO[0003] failed to create task
> error="OCI runtime create failed: args must not be empty: unknown". 

The line before says debug=false, how do I set that to true? 

Nothing shows in /var/logs/xen-tools.log

I've had a bit of a poke around but am no expert.....

> (ns: sshd) linuxkit-3219813b82be:/var/log# ctr -n services.linuxkit c ls
CONTAINER    IMAGE    RUNTIME                           
compose      -        io.containerd.runtime.v1.linux    
docker       -        io.containerd.runtime.v1.linux    
getty        -        io.containerd.runtime.v1.linux    
ntpd         -        io.containerd.runtime.v1.linux    
rngd         -        io.containerd.runtime.v1.linux    
sshd         -        io.containerd.runtime.v1.linux    
xen-tools    -        io.containerd.runtime.v1.linux    

> (ns: sshd) linuxkit-3219813b82be:/var/log# ctr -n services.linuxkit task ls
TASK       PID     STATUS    
docker     831     RUNNING
getty      871     RUNNING
ntpd       917     RUNNING
rngd       970     RUNNING
sshd       1011    RUNNING
compose    783     STOPPED

Any pointers would be great!!

**Comment by deitch** [comment]
> Then I added the service in my yml referencing the image I built, but no joy. An extra error line shows up during boot

What does your `yml` look like?

**Comment by jmccoy555** [comment]
I'm guessing there's something missing for the service xen-tools, but don't know what, and there don't appear to be any examples on Zededa, not that I could find anyway.

I tagged my local xen-tools build - linuxkit/xen-tools:local

There is also a Xen package that you linked, from looking at the Dockerfile I presume his is actually Xen itself? 

Here's my full yml (I know dind is probably not the 'official' way of doing things, but I haven't worked out how to mount NFS shares yet, if that's even possible, and it was easy just to copy my existing compose files across) and it works pretty well for my needs, and is a lot snappier than a big docker host VM........ anyway:

```
kernel:
  image: linuxkit/kernel:4.19.27
#  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
  cmdline: "console=tty0"
init:
  - linuxkit/init:005807f5c6a74e23f485a6d1657818bdccb70cd0
  - linuxkit/runc:606971451ea29b4238029804ca638f9f85caf5af
  - linuxkit/containerd:6e6841be5ad15c30752d81d121b247fa3ae08c97
  - linuxkit/ca-certificates:906c46a26fd2df271bf64c0259bf2267f7593213
onboot:
  - name: sysctl
    image: linuxkit/sysctl:713e535f2d4e4c74aba50cc7f73e3826b2dd3857
  - name: sysfs
    image: linuxkit/sysfs:21a2071205e7060ed76656960eda5434b2fdcd91
#  - name: dhcpcd
#    image: linuxkit/dhcpcd:85738d3d2f152a7879e17a61444f7714b858c2ee
#    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: ip
    image: linuxkit/ip:4787413a729748bcf7560c73e0b46d38b8a8df2b
    binds:
     - /etc/ip:/etc/ip
    command: ["ip", "-b", "/etc/ip/eth0.conf"]
  - name: format
    image: linuxkit/format:ada5fd97592c33399140f5f93f517c02f55edb14
  - name: mount
    image: linuxkit/mount:019bc551972cf2d136b443d70b4bf94c54d0d1fe
    command: ["/usr/bin/mountie", "/var/lib/docker"]
services:
  - name: getty
    image: linuxkit/getty:01993189b8c583dc91cbbc7d4be131832c0fc205
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:dc49cff2c835b196610a3f2efb585bb276658bce
  - name: ntpd
    image: linuxkit/openntpd:7f48912e995d0eb6d021b5c0d2d2a062b3b2e4d3
#  - name: open-vm-tools
#    image: linuxkit/open-vm-tools:ff7d6c5789fe82c901c8a83a20f5a4182838cb3d
  - name: xen-tools
    image: linuxkit/xen-tools:local
  - name: sshd
    image: linuxkit/sshd:6e4740bee64bf44e9913a1db4a38b5c3a5fb6ab1
  - name: docker
    image: docker:18.06.0-ce-dind
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /var/lib/docker:/var/lib/docker
     - /lib/modules:/lib/modules
     - /var/run:/var/run
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
  - name: compose
    image: linuxkitprojects/compose:local
    binds:
     - /var/run:/var/run
     - /etc/compose:/compose
files:
  - path: var/lib/docker
    directory: true
  - path: etc/compose/docker-compose.yml
    contents: |
      version: "3.5"
      services:
        unifi-controller:
          image: goofball222/unifi
          restart: always
          ports:
            - 3478:3478/udp
            - 6789:6789
            - 8080:8080
            - 8443:8443
            - 8880:8880
            - 8843:8843
          environment:
            UNIFI_GID: 1000
            UNIFI_UID: 1000
            RUNAS_UID0: "true"   
          volumes:
            - type: volume
              source: unifi-controller-data
              target: /usr/lib/unifi/data
      volumes:
        unifi-controller-data:
          driver: local
          driver_opts:
            type: nfs
            o: addr=10.10.1.125,vers=4,soft,rw
            device: ":/mnt/tank2/docker_volumes/unifi_controller/data/"
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
  - path: etc/ip/eth0.conf
    contents: |
      address add 10.10.1.160/24 dev eth0
      link set eth0 up
      route add default via 10.10.1.100 dev eth0
  - path: etc/resolv.conf
    contents: |
      nameserver 10.10.1.101
      nameserver 10.10.1.100
trust:
  org:
    - linuxkit
    - library

```

Thanks.
