### ISSUE TITLE
Priviledged containers are not possible or lack documentation

### ISSUE THREAD

**Issue by pojntfx** [linuxkit/linuxkit#3325]
While trying to create a `k3s`-OS, I wanted to use a priviledged container. Is this possible? If so, is the documentation missing?

Below is some YAML that I've though of so far:

```yaml
kernel:
  image: linuxkit/kernel:4.19.33
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:629fdad56e62ae72bf8becf0c8a668241480d3ff
  - linuxkit/runc:606971451ea29b4238029804ca638f9f85caf5af
  - linuxkit/containerd:39ac21278cfcc10dbcc32ad7f5abbe820852c5bd
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:85738d3d2f152a7879e17a61444f7714b858c2ee
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: linuxkit/getty:01993189b8c583dc91cbbc7d4be131832c0fc205
    env:
      - INSECURE=true
  - name: k3s-server
    image: rancher/k3s:v0.3.0
    command: ["/bin/k3s", "server"]
    capabilities:
      - ALL
    net: host
```

Which throws the following error, probably because I'm not able to run a priviledged container:

```bash
(ns: getty) linuxkit-0eb3bb95da41:~# cat /var/log/k3s-server.log 
time="2019-04-10T14:13:04.323530487Z" level=info msg="Starting k3s v0.3.0 (9a1a1ec)"
time="2019-04-10T14:13:05.902726168Z" level=info msg="Running kube-apiserver --watch-cache=false --cert-dir /var/lib/rancher
time="2019-04-10T14:13:06.539875497Z" level=info msg="Running kube-scheduler --kubeconfig /var/lib/rancher/k3s/server/cred/k
time="2019-04-10T14:13:06.542833776Z" level=info msg="Running kube-controller-manager --kubeconfig /var/lib/rancher/k3s/serv
Flag --address has been deprecated, see --bind-address instead.
time="2019-04-10T14:13:06.740689563Z" level=info msg="Creating CRD listenerconfigs.k3s.cattle.io"
time="2019-04-10T14:13:06.750698097Z" level=info msg="Creating CRD addons.k3s.cattle.io"
time="2019-04-10T14:13:06.760354224Z" level=info msg="Creating CRD helmcharts.k3s.cattle.io"
time="2019-04-10T14:13:06.828657222Z" level=info msg="Waiting for CRD helmcharts.k3s.cattle.io to become available"
time="2019-04-10T14:13:07.333358896Z" level=info msg="Done waiting for CRD helmcharts.k3s.cattle.io to become available"
time="2019-04-10T14:13:07.333518548Z" level=info msg="Waiting for CRD listenerconfigs.k3s.cattle.io to become available"
time="2019-04-10T14:13:07.835017642Z" level=info msg="Done waiting for CRD listenerconfigs.k3s.cattle.io to become available
time="2019-04-10T14:13:07.835073833Z" level=info msg="Waiting for CRD addons.k3s.cattle.io to become available"
time="2019-04-10T14:13:08.338738422Z" level=info msg="Done waiting for CRD addons.k3s.cattle.io to become available"
time="2019-04-10T14:13:08.346896352Z" level=info msg="Listening on :6443"
time="2019-04-10T14:13:08.990116851Z" level=info msg="Node token is available at /var/lib/rancher/k3s/server/node-token"
time="2019-04-10T14:13:08.990206395Z" level=info msg="To join node to cluster: k3s agent -s https://192.168.122.130:6443 -t 
time="2019-04-10T14:13:08.994857273Z" level=info msg="Writing static file: /var/lib/rancher/k3s/server/static/charts/traefik
time="2019-04-10T14:13:08.995526760Z" level=info msg="Writing manifest: /var/lib/rancher/k3s/server/manifests/coredns.yaml"
time="2019-04-10T14:13:08.995810012Z" level=info msg="Writing manifest: /var/lib/rancher/k3s/server/manifests/traefik.yaml"
time="2019-04-10T14:13:09.074120242Z" level=info msg="Wrote kubeconfig /etc/rancher/k3s/k3s.yaml"
time="2019-04-10T14:13:09.074194599Z" level=info msg="Run: k3s kubectl"
time="2019-04-10T14:13:09.074220385Z" level=info msg="k3s is up and running"
time="2019-04-10T14:13:09.162324701Z" level=info msg="Logging containerd to /var/lib/rancher/k3s/agent/containerd/containerd
time="2019-04-10T14:13:09.163282806Z" level=info msg="Running containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config
time="2019-04-10T14:13:09.185585510Z" level=info msg="Waiting for containerd startup: rpc error: code = Unavailable desc = a
containerd: exit status 1
```
