### ISSUE TITLE
Firmware blobs location differ between firmware and firmware-all

### ISSUE THREAD

**Issue by hyperized** [linuxkit/linuxkit#3392]
**Description**

The target paths of (at least) bnx2 firmware blobs differ between `firmware` and `firmware-all`.

**Steps to reproduce the issue:**

1. Build LinuxKit with: 
`linuxkit/firmware-all:v0.7` and boot with Getty:

```yaml
kernel:
  image: linuxkit/kernel:5.1.15
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:1a0c6b624708b5a9e58b9a608a9ce3164e7b2908
  - linuxkit/runc:c1f0db27e71d948f3134b31ce76276f843849b0a
  - linuxkit/containerd:2e7e59b8af98a1cec834dc9fe7aba271bf4b0a41
  - linuxkit/firmware-all:v0.7
services:
  - name: getty
    image: linuxkit/getty:v0.7
    env:
      - INSECURE=true
    binds:
      - /etc/resolv.conf:/etc/resolv.conf
      - /run:/run
      - /tmp:/tmp
      - /etc:/hostroot/etc
      - /usr/bin/ctr:/usr/bin/ctr
      - /usr/bin/runc:/usr/bin/runc
      - /containers:/containers
      - /var/log:/var/log
      - /var/lib/containerd:/var/lib/containerd
      - /dev:/dev
      - /sys:/sys
      - /lib/firmware:/lib/firmwware
trust:
  org:
    - linuxkit
```
And the firmware blob we need is located in:

```sh
(ns: getty) linuxkit-7e9f5485758f:~# stat /lib/firmware/bnx2/bnx2-mips-09-6.2.1.
fw
  File: /lib/firmware/bnx2/bnx2-mips-09-6.2.1.fw
  Size: 104104    	Blocks: 208        IO Block: 4096   regular file
Device: 12h/18d	Inode: 25682       Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-04-16 22:44:18.000000000
Modify: 2019-04-16 22:44:18.000000000
Change: 2019-07-29 07:28:30.000000000
```

Now if I build the following:

```yaml
kernel:
  image: linuxkit/kernel:5.1.15
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:1a0c6b624708b5a9e58b9a608a9ce3164e7b2908
  - linuxkit/runc:c1f0db27e71d948f3134b31ce76276f843849b0a
  - linuxkit/containerd:2e7e59b8af98a1cec834dc9fe7aba271bf4b0a41
  - linuxkit/firmware:v0.7
services:
  - name: getty
    image: linuxkit/getty:v0.7
    env:
      - INSECURE=true
    binds:
      - /etc/resolv.conf:/etc/resolv.conf
      - /run:/run
      - /tmp:/tmp
      - /etc:/hostroot/etc
      - /usr/bin/ctr:/usr/bin/ctr
      - /usr/bin/runc:/usr/bin/runc
      - /containers:/containers
      - /var/log:/var/log
      - /var/lib/containerd:/var/lib/containerd
      - /dev:/dev
      - /sys:/sys
      - /lib/firmware:/lib/firmwware
trust:
  org:
    - linuxkit
```

I observe the following path:
```sh
(ns: getty) linuxkit-6a9d8c438771:~# stat /lib/firmware/bnx2/bnx2-mips-06-6.2.3.
fw/bnx2-mips-06-6.2.3.fw
  File: /lib/firmware/bnx2/bnx2-mips-06-6.2.3.fw/bnx2-mips-06-6.2.3.fw
  Size: 92824     	Blocks: 184        IO Block: 4096   regular file
Device: 12h/18d	Inode: 22923       Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-04-16 22:39:43.000000000
Modify: 2019-04-16 22:39:43.000000000
Change: 2019-07-29 07:32:38.000000000
```
Notice it's now a directory named after the firmware file containing the firmware file.

Now I'm not sure if this is by design, but it seems odd. In the location of the `firmware` package the kernel seems to be unable to locate the blob and in our case we can't use these network drivers.

We would much prefer to use the `firmware` (841 KB) package since it contains just the drivers we need rather than all the `firmware-all` (181 MB) blobs due to it's increased size

Can someone elaborate on this?

**Comment by rn** [comment]
I can't reproduce this. I'm using:

```
kernel:
  image: linuxkit/kernel:4.19.56
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:1a0c6b624708b5a9e58b9a608a9ce3164e7b2908
  - linuxkit/runc:c1f0db27e71d948f3134b31ce76276f843849b0a
  - linuxkit/containerd:2e7e59b8af98a1cec834dc9fe7aba271bf4b0a41
  - linuxkit/firmware:v0.7
  - linuxkit/getty:v0.7
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.7
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
trust:
  org:
    - linuxkit
```
and then just replace `linuxkit/firmware:v0.7` with `linuxkit/firmware-all:v0.7` and I get the same directory layout in `/lib/firmware`, e.g. `/lib/firmware/bnx2/bnx2-mips-06-6.2.3.fw` is a directory in both cases
