### ISSUE TITLE
Ability to add additonal "layers"

### ISSUE THREAD

**Issue by rmb938** [linuxkit/linuxkit#3405]
I have a use case where I have a "base" yaml configuration file to build a LinuxKit image. I then would like to take that base image and add things to it. i.e change configuration, add additional packages ect... Somewhat similar to docker images where I can expand upon and add more layers to existing images.

Currently to get this effect I need a full yaml definition, add the additional things and rebuild the whole thing. 

It would be nice to be able to have something like this:

base.yml
```
kernel:
  image: linuxkit/kernel:4.19.52
  cmdline: "console=tty0 console=tty1 console=ttyS0 kubeadm=init"
init:
  - linuxkit/init:1d8e0532ca588c5ad0d9ca6038349a70bb7ac626
  - linuxkit/runc:c1f0db27e71d948f3134b31ce76276f843849b0a
  - linuxkit/containerd:751de142273e1b5d2d247d2832d654ab92e907bc
  - linuxkit/ca-certificates:v0.7
  - linuxkit/memlogd:v0.7
onboot:
  - name: dhcpcd1
    image: linuxkit/dhcpcd:v0.7
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: linuxkit/getty:v0.7
  - name: sshd
    image: linuxkit/sshd:v0.7
```

Then I could build the base into a tar or docker image or other format.

And have an "app.yaml" for example with the following contents:
``
from: base.tar
services:
  - name: ntpd
    image: linuxkit/openntpd:v0.7
files:
  - path: /run/config/ssh/authorized_keys
    source: .ssh/id_rsa.pub
    mode: "0600"
    optional: true
``

Then build the app and it would download or extract or something the base image and add the additional things that where specified.

Thoughts?
