### ISSUE TITLE
build -format rpi3 could not add file or folder

### ISSUE THREAD

**Issue by taskx6004** [linuxkit/linuxkit#3415]
Hi,

I have tested minimal.yml and dhcp configure successfully on rpi3 format, but I could not run static-ip.yml sample due to /etc/ip/eth0.conf file and ip folder is missing.

I have tried to make directory "ip" and created eth0.conf file in build directory, and added:
```
files:
  - path: /etc/ip
    directory: true
    mode: "0777"
```
still no effect.

I suspect something wrong with the -format rpi3 attribute was executed in the build system, if i was doing something wrong, please correct me.

Thanks.
