### ISSUE TITLE
Unclear how to access console with a `docker run`

### ISSUE THREAD

**Issue by cdbattags** [linuxkit/linuxkit#3467]
**Description**

Unclear how to access console with a `docker run`.

Thanks @justincormack for all your [help so far on Twitter](https://twitter.com/justincormack/status/1221883379559301127). 

**Steps to reproduce the issue:**

yaml file:

```yml
kernel:
  image: linuxkit/kernel:4.19.90
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:a4fcf333298f644dfac6adf680b83140927aa85e
trust:
  org:
    - linuxkit
```

then a quick bash script

```bash
linuxkit build -format docker sshd.yml

LAST_LINE=`cat sshd.docker | docker build - | tail -n 1`

IMAGE_SHA=`echo $LAST_LINE | rg '(.+)\s(\w+)$' -r '$2'`

docker run $IMAGE_SHA
```

then I'm trying to access the console

```
docker exec -it <container-name> "<what-goes-here?>"
```

**Describe the results you received:**

```
Extract kernel image: docker.io/linuxkit/kernel:4.19.90
WARN[0001] targets/justin metadata is nearing expiry, you should re-sign the role metadata
Add init containers:
Process init image: docker.io/linuxkit/init:a4fcf333298f644dfac6adf680b83140927aa85e
Process init image: docker.io/linuxkit/getty:v0.7
  Adding Dockerfile
2020/01/28 03:36:09 Setting hostname failed: operation not permitted
getty: cmdline has console=ttyS0 but /dev/ttyS0 is not a character device; not starting getty for ttyS0
getty: cmdline has console=ttyS1 but /dev/ttyS1 is not a character device; not starting getty for ttyS1
```

**Describe the results you expected:**

I expect some way to access some sort of console inside the container. Or am I going about this the wrong way? Any chance to get a plain ol' bash shell for debugging around the unikernel to get started?

**Additional information you deem important (e.g. issue happens only occasionally):**

N/A
