### ISSUE TITLE
SocketCAN & vcan support

### ISSUE THREAD

**Issue by Clovel** [linuxkit/linuxkit#3485]
## Description
I would like to use SocketCAN's `vcan` feature in a Docker container using [Docker for Mac](https://github.com/docker/for-mac/), which is based on LinuxKit. 

## Action 
Linux Kernel (LinuxKit) should have the following configuration flags for a (near) full CAN protocol support : 
```config
#
# CAN Bus support
#

CONFIG_CAN=m
CONFIG_CAN_RAW=m
CONFIG_CAN_BCM=m
CONFIG_CAN_GW=m

#
# CAN Device Drivers
#
CONFIG_CAN_VCAN=m
CONFIG_CAN_SLCAN=m
CONFIG_CAN_DEV=m
CONFIG_CAN_CALC_BITTIMING=y
CONFIG_CAN_MCP251X=m
CONFIG_PCH_CAN=m
CONFIG_CAN_SJA1000=m
CONFIG_CAN_SJA1000_PLATFORM=m
CONFIG_CAN_EMS_PCMCIA=m
CONFIG_CAN_EMS_PCI=m
CONFIG_CAN_PEAK_PCI=m
CONFIG_CAN_KVASER_PCI=m
CONFIG_CAN_PLX_PCI=m
CONFIG_CAN_C_CAN=m

#
# CAN USB interfaces
#
CONFIG_CAN_EMS_USB=m
CONFIG_CAN_ESD_USB2=m
CONFIG_CAN_SOFTING=m
CONFIG_CAN_SOFTING_CS=m
# CONFIG_CAN_DEBUG_DEVICES is not set
```

For a more streamlined and lightweight approach, maybe this could suffice : 
```config

#
# CAN Bus support
#

CONFIG_CAN=m
CONFIG_CAN_RAW=m
CONFIG_CAN_BCM=m
CONFIG_CAN_GW=m

#
# CAN Device Drivers
#
CONFIG_CAN_VCAN=m
CONFIG_CAN_DEV=m
```

## Question
The Docker for Mac LinuxKit kernel (`4.19.76-linuxkit`) is not compiled with CAN/VCAN capabilities. I wish to submit a PR adding the correct flags to the kernel configuration file, but I am not sure which ones are used by the Docker for Mac project. 

For now, I have identified these files : 
```bash
$ tree -f . | grep config-
│   ├── ./kernel/config-4.14.x-x86_64
│   ├── ./kernel/config-4.19.x-aarch64
│   ├── ./kernel/config-4.19.x-aarch64-rt
│   ├── ./kernel/config-4.19.x-x86_64
│   ├── ./kernel/config-4.19.x-x86_64-rt
│   ├── ./kernel/config-5.4.x-aarch64
│   ├── ./kernel/config-5.4.x-s390x
│   ├── ./kernel/config-5.4.x-x86_64
│   ├── ./kernel/config-dbg
```

Are these the correct place to set the configuration flags ? 

**Additional information**
I also opened an issue over at the Docker for Mac project : docker/for-mac/issues/4405. Additional information can be found there.

**Comment by Clovel** [comment]
PR submitted : #3486.

**Comment by Clovel** [comment]
I built the image using the changes from #3486, but I don't seem to be having the expected behavior : 

# vcan.yaml
```yaml
kernel:
  image: linuxkit/kernel:5.4.28
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:a0246dd478a24abbee0a4cede99662ffc4931691
  - linuxkit/runc:69b4a35eaa22eba4990ee52cccc8f48f6c08ed03
  - linuxkit/containerd:09553963ed9da626c25cf8acdf6d62ec37645412
  - linuxkit/ca-certificates:v0.7
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.7
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.7
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: modprobe
    image: linuxkit/modprobe:v0.7
    command: ["modprobe", "vcan"]
onshutdown:
  - name: shutdown
    image: busybox:latest
    command: ["/bin/echo", "so long and thanks for all the fish"]
services:
  - name: getty
    image: linuxkit/getty:v0.7
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:02c555b50cd1887aa628836662d2eec54c0d7e81
  - name: nginx
    image: nginx:1.13.8-alpine
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
files:
  - path: etc/linuxkit-config
    metadata: yaml
trust:
  org:
    - linuxkit
    - library

```
# LinuxKit build
```bash
$ make
$ ./bin/linuxkit build vcan.yaml
$ ./bin/linuxkit run vcan
```
Once I'm in the container : 
```bash
# modprobe vcan
modprobe: can't change directory to '/lib/modules': No such file or directory

# lsmod
Module                  Size  Used by    Tainted: G  
vmw_vsock_virtio_transport    20480  0 
vmw_vsock_virtio_transport_common    28672  1 vmw_vsock_virtio_transport
vsock                  36864  2 vmw_vsock_virtio_transport,vmw_vsock_virtio_transport_common

# find /lib -type d
lib
lib/mdev
lib/firmware
lib/apk
lib/apk/db
```
