### ISSUE TITLE
Binaries build for different arches are identical

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#3522]
Looking at the binaries built by actions for a release, e.g.:
https://github.com/linuxkit/linuxkit/actions/runs/101839925

all the binaries build for different architectures and OSes are identical (all are 64bit Linux binaries)

**Comment by rn** [comment]
As @deitch pointed out:
The actual build phase is at https://github.com/linuxkit/linuxkit/blob/master/.github/workflows/ci.yml#L44-L48:
```
    - name: Build
      run: |
        make LOCAL_TARGET=bin/linuxkit-${{matrix.arch}} local-build
      env:
        GOPATH: ${{runner.workspace}}
```
which in turn just does this from the Makefile https://github.com/linuxkit/linuxkit/blob/master/Makefile#L87-L88:
```
local-static: $(LINUXKIT_DEPS) | bin
	CGO_ENABLED=0 go build -o $(LOCAL_TARGET) --ldflags “$(LOCAL_LDFLAGS)” github.com/linuxkit/linuxkit/src/cmd/linuxkit
```
It doesn’t set the GOOS or GOARCH anywhere. We need to change the ci.yml to pass it the GOOS and GOARCH.
