### ISSUE TITLE
OS hang after v0.8 upgrade.

### ISSUE THREAD

**Issue by the-maldridge** [linuxkit/linuxkit#3529]
**Description**

I upgraded all components to the v0.8 tag and attempted to use a 5.6 series kernel in my ResinStack images that run on AWS.  I have since noticed that after some time the instances uniformly fail instance health checks, and restarting services fails with the following error:

```
Stopping service: "consul"
time="2020-05-20T18:49:34Z" level=fatal msg="deleting task" error="task must be stopped before deletion: running: failed precondition" service=consul
```

**Steps to reproduce the issue:**

Build an image from https://github.com/resinstack/resinstack/tree/95c8f56a57b90a721842da72d1743524b3b5148c, deploy it, wait.

**Describe the results you received:**

I received an image that hangs after some time, and that also fails to restart services.

**Describe the results you expected:**

I expected stability, and baring that running tasks.

**Additional information you deem important (e.g. issue happens only occasionally):**

So far this happens uniformly, but I'm not sure why.  I'm in the process of rolling back all init containers to 0.7 and testing there.  I'm on Slack at odd hours of the day, if there's info that would be helpful ping me and I'll update this issue.

**Comment by Ender-events** [comment]
It seems we have the same problem, every 24 hours I can't connect to the machine.
I try to figure out which container create this bug, it's probably sysctl or dhcpcd from onboot section. I will update all container except this two. I'll keep you updated but i wait more than 48 hours between each upgrade.

**Comment by the-maldridge** [comment]
I have been able to upgrade all of the linuxkit containers to v0.8 with the exception of `linuxkit/init`, `linuxkit/runc`, and `linuxkit/containerd`.  I am also seemingly stuck on a 4.19 series kernel as any attempt to upgrade that hangs the system as well.

**Comment by tristanls** [comment]
I ran the following experiment.

The following specification served as the base for this experiment:
```
kernel:
  image: linuxkit/kernel:5.4.39
  cmdline: "console=ttyS0"
init:
  - linuxkit/init:v0.8
  - linuxkit/runc:v0.8
  - linuxkit/containerd:v0.8
  - linuxkit/ca-certificates:v0.8
  - linuxkit/memlogd:v0.8
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.8
  - name: rngd
    image: linuxkit/rngd:v0.8
    command: ["/sbin/rngd", "-1"]
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.8
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: logwrite
    image: linuxkit/logwrite:v0.8
  - name: kmsg
    image: linuxkit/kmsg:v0.8
  - name: sshd
    image: linuxkit/sshd:v0.8
files:
  - path: etc/init.d/002-logging
    contents: |
      #!/bin/sh

      /usr/bin/memlogd -daemonize -max-line-len 12288
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/me.pub
    mode: "0600"
    optional: true
trust:
  org:
    - linuxkit
    - library
```
I created images where everything is v0.8 `v0.8`, then I created image where everything in `init` section is v0.7 `v0.8-init-v0.7`, then I created image where everything in `onboot` sections is v0.7 `v0.8-onboot-v0.7`, then I created image where everything in `services` section is v0.7 `v0.8-services-v0.7`. For example:
```
$ linuxkit build -format aws -size 256M -name amzn-ec2-t3-20200522-v0.8-onboot-v0.7 amzn-ec2-t3.yaml
```
I registered all the images and launched each one on a `t3.micro` instance.
I observed the following timeline:
```
09:24 launched instances
v0.8
v0.8-init-v0.7
v0.8-onboot-v0.7
v0.8-services-v0.7

09:25 SSH to all instances succeeds

09:26 v0.8-onboot-v0.7 Status Check is still “initializing” (others are good)

09:27 SSH to all instances succeeds; all Status Checks are good for all instances

09:28 System Log unavailable for all instances

09:33 SSH to all instances succeeds

09:49 SSH to all instances succeeds

09:53 SSH to all instances succeeds; System Logs are now available

10:02 SSH to all instances succeeds

10:12 SSH to all instances succeeds

10:20 SSH to all instances succeeds

10:25 only v0.8-onboot-v0.7 continues to respond to SSH, other instances are unresponsive to SSH

10:29 only v0.8-onboot-v0.7 continues to pass Instance Status Checks and respond to SSH, other instances fail

10:35 only v0.8-onboot-v0.7 continues to pass Instance Status Checks and respond to SSH, other instances fail
```

Currently, I'm generating images to isolate `sysctl`, `rngd`, `dhcpcd`.
