### ISSUE TITLE
Read env vars for command args

### ISSUE THREAD

**Issue by ulm0** [linuxkit/linuxkit#3537]
**Description**
is there a way to read env vars values for comand args params?

e.g.:

```yaml
...
services:
  - name: some-service
    image: user/container
    env:
      - MY_SUPER_ENV=mysupervalue
    command:
      - /path/to/bin
      - --some-flag=$MY_SUPER_ENV
...
```

i've tried `$MY_SUPER_ENV`, `${MY_SUPER_ENV}` and `$(MY_SUPER_ENV)` so far and none of those works, reading the logs for `some-service` `MY_SUPER_ENV` is not replaced with its actual value.

in the same note, is it possible to set env vars to `MY_SUPER_ENV=$(command)`?

**Steps to reproduce the issue:**

Set an env var for a service and use it as arg param

**Describe the results you received:**

Value no being set

**Describe the results you expected:**

To `--some-flag` value to be set to `mysupervalue`

**Additional information you deem important (e.g. issue happens only occasionally):**

```yaml
...
services:
  - name: k3s
    image: rancher/k3s:v1.18.4-k3s1
    env:
      - MASTER_IP=$(/sbin/ifconfig eth0|grep 'inet addr'| cut -d":" -f2 | awk '{ print $1}')
    capabilities:
      - all
    net: host
    command: 
      - /bin/k3s
      - server
      - --bind-address=$MASTER_IP
      - --node-external-ip=$MASTER_IP
      - --node-ip=$MASTER_IP
    mounts:
      - type: bind
        source: /sys/fs/cgroup
        destination: /sys/fs/cgroup
        options: ["rw","rbind","rshared","nosuid","noexec","nodev","relatime"]
    runtime:
      mkdir:
        - /var/lib/rancher
    binds:
      - /var/lib/etc-rancher:/etc/rancher
      - /etc/resolv.conf:/etc/resolv.conf
      - /lib/modules:/lib/modules
      - /dev/kmsg:/dev/kmsg
      - /var/lib/rancher:/var/lib/rancher
...
```
