### ISSUE TITLE
Stability issues on GCP - network or halt issue

### ISSUE THREAD

**Issue by asbjornenge** [linuxkit/linuxkit#3560]
When building on mac I keep seeing `qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]` 🤔

I've been having trouble with these images suddenly halting on GCP for no apparent reason (nothing in logs or anything) 🤷‍♂️

```
❯ linuxkit version
linuxkit version v0.8
commit: 00b9bb56a0ca46a7298964d79ce88769bef25312
```

yaml file:

```
kernel:
  image: linuxkit/kernel:5.4.39 
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:v0.8
  - linuxkit/runc:v0.8
  - linuxkit/containerd:v0.8
  - linuxkit/ca-certificates:v0.8
  - linuxkit/memlogd:v0.8
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.8
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.8
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: sysfs
    image: linuxkit/sysfs:v0.8
  - name: format
    image: linuxkit/format:v0.8
    command: ["/usr/bin/format", "-type", "ext4", "/dev/sda"]
  - name: format-sdb
    image: linuxkit/format:v0.8
    command: ["/usr/bin/format", "-type", "ext4", "/dev/sdb"]
  - name: extend
    image: linuxkit/extend:v0.8
  - name: mount
    image: linuxkit/mount:v0.8
    command: ["/usr/bin/mountie", "-device", "/dev/sda1", "/var/disks/root"]
  - name: mount-ext
    image: linuxkit/mount:v0.8
    command: ["/usr/bin/mountie", "-device", "/dev/sdb1", "/var/disks/data"]
onshutdown:
  - name: shutdown
    image: busybox:latest
    command: ["/bin/echo", "so long and thanks for all the fish"]
services:
  - name: getty
    image: linuxkit/getty:v0.8
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:v0.8
  - name: ntpd
    image: linuxkit/openntpd:v0.8
  - name: docker
    image: docker:19.03.8-dind 
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /var/disks/data/docker:/var/lib/docker
     - /var/run/memlogdq.sock:/var/run/memlogdq.sock
     - /lib/modules:/lib/modules
     - /etc/docker/daemon.json:/etc/docker/daemon.json
    runtime:
      mkdir:
        - /var/disks/data/docker
  - name: sshd
    image: linuxkit/sshd:v0.8
    pid: host
    binds:
     - /var/disks/data/ssh:/etc/ssh
     - /usr/bin/ssh.sh:/usr/bin/ssh.sh
     - /root/.ssh:/root/.ssh
     - /etc/resolv.conf:/etc/resolv.conf
     - /etc/sshd_config:/etc/sshd_config
     - /run:/run
     - /tmp:/tmp
     - /etc:/hostroot/etc
     - /usr/bin/ctr:/usr/bin/ctr
     - /usr/bin/runc:/usr/bin/runc
     - /containers:/containers
     - /var/log:/var/log
     - /var/lib/containerd:/var/lib/containerd
     - /dev:/dev
     - /sys:/sys
    capabilities:
     - all
    runtime:
      mkdir:
        - /var/disks/data/ssh
files:
  - path: var/disks/root
    directory: true
  - path: var/disks/data
    directory: true
  - path: etc/sshd_config 
    source: "sshd_config"
    mode: "0700"
  - path: usr/bin/ssh.sh
    source: "ssh.sh"
    mode: "0700"
  - path: root/.ssh/authorized_keys 
    contents: | 
      ssh-rsa <my-pubkey>
  - path: etc/docker/daemon.json
    contents: | 
      {
        "hosts": ["unix:///var/run/docker.sock","0.0.0.0:4243"],
        "insecure-registries": ["registry.taghub.swarm:5000"]
      }
trust:
  org:
    - linuxkit
    - library
```

Any and all ideas heartly welcomed 😅❤️
