### ISSUE TITLE
Issues with cloud-init in libvirt/kvm

### ISSUE THREAD

**Issue by ulm0** [linuxkit/linuxkit#3565]
**Description**

I'm trying to deploy a vm on kvm using terraform, the machine is created and ip is assigned but, user-data is not being executed, log says file can't be unmarshaled.

**Steps to reproduce the issue:**
- Create linuxkit image (`linuxkit build -format kernel+initrd k3s.yml`)
<details open>
<summary>k3s.yml</summary>
<br>

```yml
kernel:
  image: linuxkit/kernel:5.4.39
  cmdline: "console=tty0 page_poison=1"
init:
  - linuxkit/init:v0.8
  - linuxkit/runc:v0.8
  - linuxkit/containerd:v0.8
  - linuxkit/ca-certificates:v0.8
onboot:
  - name: metadata
    image: linuxkit/metadata:v0.8
  - name: sysctl
    image: linuxkit/sysctl:v0.8
    binds:
     - /etc/sysctl.d/01-k3s.conf:/etc/sysctl.d/01-k3s.conf
  - name: sysfs
    image: linuxkit/sysfs:v0.8
  - name: format
    image: linuxkit/format:v0.8
    command: ["/usr/bin/format", "-force", "-verbose", "-type", "ext4", "-label", "ephemeral0", "/dev/vda"]
  - name: mount
    image: linuxkit/mount:v0.8
    command: ["/usr/bin/mountie", "-label", "ephemeral0", "/var/lib"]
  - name: move-logs
    image: busybox:latest
    binds:
      - /var:/host_var
    command: ["/bin/sh", "-c", "mv -v /host_var/log /host_var/lib && ln -vs /var/lib/log /host_var/log"]
  - name: mkdir
    image: busybox:latest
    binds:
      - /var/lib:/host_var_lib
    command: ["/bin/sh", "-c", "mkdir -p /host_var_lib/rancher /host_var_lib/etc-rancher"]
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.8
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  # - name: qemu-ga
  #   image: linuxkit/qemu-ga:v0.8
  #   # binds:
  #   #   - /dev/vport0p1:/dev/vport0p1
  #   # command: ["/usr/bin/qemu-ga", "-p", "/dev/vport1p1"]
  #   capabilities:
  #     - all
  #   net: host
  #   pid: host
  - name: rngd
    image: linuxkit/rngd:v0.8
    cgroupsPath: systemreserved/rngd
  - name: acpid
    image: linuxkit/acpid:v0.8
    cgroupsPath: systemreserved/acpid
  - name: ntpd
    image: linuxkit/openntpd:v0.8
    cgroupsPath: systemreserved/ntpd
  - name: host-timesync-daemon
    image: linuxkit/host-timesync-daemon:v0.8
    cgroupsPath: systemreserved/host-timesync-daemon
  - name: k3s
    image: rancher/k3s:v1.19.3-k3s1
    capabilities:
      - all
    net: host
    pid: host
    command:
      - sh
      - /bin/rancher/k3s-helper
    mounts:
      - type: bind
        source: /sys/fs/cgroup
        destination: /sys/fs/cgroup
        options: ["rw","rbind","rshared","nosuid","noexec","nodev","relatime"]
      - type: bind
        source: /sys/fs/bpf
        destination: /sys/fs/bpf
        options: ["rw","rbind","rshared","nosuid","noexec","nodev","relatime"]
    runtime:
      cgroups:
        - kubepods
        - podruntime
        - systemreserved
    binds:
      - /dev:/dev
      - /etc/os-release:/etc/os-release
      - /etc/resolv.conf:/etc/resolv.conf
      - /lib/modules:/lib/modules
      - /run/config/rancher:/bin/rancher
      - /var/lib/etc-rancher:/etc/rancher
      - /var/lib/rancher:/var/lib/rancher
    rootfsPropagation: shared
    cgroupsPath: podruntime/k3s
  - name: getty
    image: linuxkit/getty:v0.8
    env:
      - INSECURE=true
    binds.add:
      - /boot:/boot
      - /etc/motd:/etc/motd
      - /var/lib/etc-rancher:/etc/rancher
      - /var/lib/rancher:/var/lib/rancher
      - /:/hostroot
    cgroupsPath: systemreserved/getty
  - name: sshd
    image: linuxkit/sshd:v0.8
    binds.add:
      - /boot:/boot
      - /etc/motd:/etc/motd
      - /var/lib/etc-rancher:/etc/rancher
      - /var/lib/rancher:/var/lib/rancher
      - /:/hostroot
    cgroupsPath: systemreserved/sshd

files:
  - path: etc/linuxkit.yml
    metadata: yaml
  - path: etc/motd
    contents: |
      __   ___     _   _ _   
      | |_|_  |___| |_|_| |_ 
      | '_|_  |_ -| '_| |  _|
      |_,_|___|___|_,_|_|_|

      Built by: ulm0 <ulm0@innersea.xyz>
      Project on GitHub: https://github.com/ulm0/k3skit

    mode: "0644"
  - path: /etc/os-release
    contents: |
      NAME="k3skit"
      ID="k3skit"
      PRETTY_NAME="k3skit"
      HOME_URL="https://github.com/ulm0/k3skit"
      BUG_REPORT_URL="https://github.com/ulm0/k3skit/issues"
  # - path: root/.ssh/authorized_keys
  #   source: ~/.ssh/id_rsa.pub
  #   mode: "0600"
  #   optional: true
  - path: /etc/sysctl.d/01-k3s.conf
    contents: |
      net.ipv4.ip_forward=1
      # iptables setting needed by br_netfilter module
      # net.bridge.bridge-nf-call-iptables=1

      ## Tuning ARP cache

      net.ipv4.neigh.default.gc_thresh1=80000
      net.ipv4.neigh.default.gc_thresh2=90000
      net.ipv4.neigh.default.gc_thresh3=100000

      ##
      # Node optimizations
      # (https://github.com/kubernetes/kops/blob/afb4ecb883142e3dad0a960149b25b1094fe4f69/nodeup/pkg/model/sysctls.go#L35)
      ##

      # Increase the number of connections
      net.core.somaxconn=32768
      # Maximum Socket Receive Buffer
      net.core.rmem_max=16777216
      # Maximum Socket Send Buffer
      net.core.wmem_max=16777216
      # Increase the maximum total buffer-space allocatable
      net.ipv4.tcp_wmem="4096 12582912 16777216"
      net.ipv4.tcp_rmem="4096 12582912 16777216"
      # Increase the number of outstanding syn requests allowed
      net.ipv4.tcp_max_syn_backlog=8096
      # For persistent HTTP connections
      net.ipv4.tcp_slow_start_after_idle=0
      # Allow to reuse TIME_WAIT sockets for new connections when it is safe from protocol viewpoint
      net.ipv4.tcp_tw_reuse=1
      # Can't change the local_port_range without changing the NodePort range
      # Allowed local port range
      # net.ipv4.ip_local_port_range="1024 65000"
      # Max number of packets that can be queued on interface input
      # If kernel is receiving packets faster than can be processed
      # this queue increases
      net.core.netdev_max_backlog=16384
      # Increase size of file handles and inode cache
      fs.file-max=2097152
      # Max number of inotify instances and watches for a user",
      # Since dockerd runs as a single user, the default instances value of 128 per user is too low
      # e.g. uses of inotify: nginx ingress controller, kubectl logs -f
      fs.inotify.max_user_instances=8192
      fs.inotify.max_user_watches=524288

trust:
  org:
    - linuxkit
    - library
```
 
</details>

- use artifacts and deploy them with terraform

<details open>
<summary>main.tf</summary>
<br>

```hcl
terraform {
  required_version = ">= 0.13"
  required_providers {
    libvirt = {
      source  = "dmacvicar/libvirt"
      version = "0.6.2"
    }
  }
}

variable private_key_filename { default = "./default.pem" }

provider libvirt {
  uri = "qemu:///system"
}

resource tls_private_key default {
  algorithm = "RSA"
  rsa_bits  = "4096"
}

resource local_file private_key_pem {
  filename = var.private_key_filename
  content  = tls_private_key.default.private_key_pem

  provisioner "local-exec" {
    command = format("chmod 600 %s", var.private_key_filename)
  }
}

resource libvirt_pool linuxkit {
  name = "linuxkit"
  type = "dir"
  path = "/tmp/terraform-provider-libvirt-pool-linuxkit"
}

resource libvirt_volume linuxkit_template {
  name   = "linuxkit-template.img"
  pool   = libvirt_pool.linuxkit.name
  source = "../k3s-initrd.img"
  format = "raw"
}

resource libvirt_volume linuxkit {
  name   = "linuxkit.img"
  pool   = libvirt_pool.linuxkit.name
  size   = 20 * 1024 * 1024 * 1024 # Size in bytes (N  (GiB) * 1024 (MiB) * 1024 (KiB) * 1024 (Bytes))
  format = "raw"
}

resource libvirt_volume kernel {
  source = "../k3s-kernel"
  name   = "linuxkit-kernel"
  pool   = libvirt_pool.linuxkit.name
  format = "raw"
}

data template_file user_data {
  template = file(format("%s/files/cloud_init.yml", path.module))
  vars = {
    authorized_key = tls_private_key.default.public_key_openssh
  }
}

data template_file meta_data {
  template = file(format("%s/files/metadata.yml", path.module))
}

resource libvirt_cloudinit_disk common_init {
  name      = "commoninit.iso"
  user_data = data.template_file.user_data.rendered
  meta_data = data.template_file.meta_data.rendered
  pool      = libvirt_pool.linuxkit.name
}

resource libvirt_domain linuxkit {
  name       = "linuxkit-terraform"
  memory     = "2048"
  vcpu       = 1
  qemu_agent = true
  kernel     = libvirt_volume.kernel.id
  initrd     = libvirt_volume.linuxkit_template.id
  cmdline = [
    {
      console     = "tty0"
      page_poison = "1"
    }
  ]

  cloudinit = libvirt_cloudinit_disk.common_init.id

  network_interface {
    network_name   = "default"
    hostname       = "linuxkit-terraform"
    wait_for_lease = true
  }

  # IMPORTANT: this is a known bug on cloud images, since they expect a console
  # we need to pass it
  # https://bugs.launchpad.net/cloud-images/+bug/1573095
  console {
    type        = "pty"
    target_port = "0"
    target_type = "serial"
  }

  console {
    type        = "pty"
    target_type = "virtio"
    target_port = "1"
  }


  disk {
    volume_id = libvirt_volume.linuxkit.id
  }

  graphics {
    type        = "spice"
    listen_type = "address"
    autoport    = true
  }
}

output ip {
  value = libvirt_domain.linuxkit.network_interface.0.addresses
}
```

</details>

<details open>
<summary>cloud_init.yml</summary>
<br>

```yml
#cloud-config
# vim: syntax=yaml

ssh_authorized_keys:
  - ${authorized_key}
final_message: "The system is finally up, after $UPTIME seconds"
```
</details>

<details open>
<summary>metadata.yml</summary>
<br>

```yml
rancher:
  entries:
    k3s-helper:
      content: |
        export MASTER_IP=$$(/bin/ifconfig eth0|grep 'inet addr'| cut -d: -f2 | awk '{ print $1 }')
        /bin/k3s \
          server \
            --bind-address=$${MASTER_IP} \
            --disable-kube-proxy \
            --disable=traefik \
            --flannel-backend=none \
            --kube-controller-manager-arg=allocate-node-cidrs=true \
            --kube-controller-manager-arg=node-monitor-grace-period=15s \
            --kube-controller-manager-arg=node-monitor-period=2s \
            --kube-controller-manager-arg=pod-eviction-timeout=30s \
            --kubelet-arg=cgroup-root=kubepods \
            --kubelet-arg=kube-reserved-cgroup=podruntime \
            --kubelet-arg=node-status-update-frequency=4s \
            --kubelet-arg=system-reserved-cgroup=systemreserved \
            --node-external-ip=$${MASTER_IP} \
            --node-ip=$${MASTER_IP} \
            --secrets-encryption
      perm: "0755"
```

</details>

**Describe the results you received:**

metadata package is unable to unmarshal user-data file

```sh
(ns: sshd) linuxkit-525400ee0ad6:~# cat /hostroot/var/lib/log/onboot/onboot.000-metadata.log 
2020/10/22 15:35:22 Scaleway: Could not contact metadata service: Get http://169.254.42.42/conf: dial tcp 169.254.42.42:80: connect: network is unreachable
Trying CDROM /dev/sr0
CDROM /dev/sr0: Probe succeeded
Could not unmarshall userdata: invalid character '#' looking for beginning of value
```

**Describe the results you expected:**

metadata works from given user-data file

**Additional information you deem important (e.g. issue happens only occasionally):**

cloud-init.iso contains both user-data and metada files, but only user-data is created in guest

```sh
(ns: sshd) linuxkit-525400ee0ad6:~# ls /run/config/
provider  userdata
```
