### ISSUE TITLE
Elasticsearch container doesn't works : chroot not find in entrypoint

### ISSUE THREAD

**Issue by Pierre-Monier** [linuxkit/linuxkit#3621]
lsb_release -a : 
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

linuxkit version : 
```
linuxkit version v0.8+
commit: e48d5294ee7958d277f46d6b5ea560a910cb554c
```

**Description**
I'm trying to build an iso image which contains the elastic stack. 

```yml
kernel:
  image: linuxkit/kernel:5.4.39
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:a68f9fa0c1d9dbfc9c23663749a0b7ac510cbe1c
  - linuxkit/runc:v0.8
  - linuxkit/containerd:1ae8f054e9fe792d1dbdb9a65f1b5e14491cb106
  - linuxkit/ca-certificates:v0.8
  - linuxkit/memlogd:v0.8
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.8
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.8
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: linuxkit/getty:v0.8
    env:
     - INSECURE=true
  - name: elastic
    image: elasticsearch:6.8.15
    net: host
    env:
      - discovery.type=single-node
    capabilities:
      - all
  - name: apm
    image: docker.elastic.co/apm/apm-server:7.12.0
    net: host
    capabilities:
      - all
  - name: write-and-rotate-logs
    image: linuxkit/logwrite:v0.8
files:
  - path: etc/linuxkit-config
    metadata: yaml
  - path: /etc/containerd/runtime-config.toml
    source: "~/Code/linuxkitElasticstack/utils/runtime-config.toml"
    mode: "0644"
trust:
  org:
    - linuxkit
```

Here is my runtime-config.toml : 
```
cliopts="--log-level debug"
stderr="/var/log/containerd.err.log"
stdout="/var/log/containerd.out.log"
```

I'm building it with `linuxkit build -format iso-bios elasticstack.yml` and running it with `linuxkit run qemu elasticstack.iso`

The problem is that the elastic service isn't starting properly because the **official** entrypoint script is throwing an error 

```
2021-04-07T14:38:07Z elastic /usr/local/bin/docker-entrypoint.sh: line 10: exec: chroot: not found
```
Here is a link to the official [entrypoint script](https://github.com/elastic/elasticsearch/blob/7.12/distribution/docker/src/docker/bin/docker-entrypoint.sh)

**Steps to reproduce the issue:**
Copy/paste the yml and the toml config file. Build with the command and run it. Then use `cat /var/log/elastic.log ` to print the log.

Tell me if I'm missing something obvious and if there is a more appropriated place like a discord server for this kind of issue
