### ISSUE TITLE
How to configure the console keymap?

### ISSUE THREAD

**Issue by rgl** [linuxkit/linuxkit#3680]
**Description**

I want to configure the console keymap.

**Steps to reproduce the issue:**

I've create a `build.yml` with:

```yml
# see https://github.com/linuxkit/linuxkit/blob/master/docs/packages.md
image: vconsole
config:
  binds:
    - /dev/console:/dev/console
```

I've created a `Dockerfile` with:

```dockerfile
FROM alpine:3.13 AS build
RUN apk add --no-cache kbd-bkeymaps
COPY --chmod=655 main.sh /
CMD ["/main.sh"]
```

I've created a `main.sh` with:

```bash
#!/bin/sh
exec 2>&1
set -x
# TODO parse /proc/cmdline for vconsole.keymap=<keymap> value.
#      like https://www.freedesktop.org/software/systemd/man/vconsole.conf.html
zcat /usr/share/bkeymaps/pt/pt.bmap.gz | loadkmap
```

And finally, my example (everything else is like [examples/ssh.yml](https://github.com/linuxkit/linuxkit/blob/master/examples/sshd.yml)) linuxkit relevant part:

```yml
onboot:
  - name: vconsole
    image: linuxkit/vconsole:latest
```

**Describe the results you received:**

The keyboard map is still configured as `us`.

Please note that `/var/log/onboot/onboot.002-vconsole.out.log` did not show any errors.

**Describe the results you expected:**

The keyboard map to be correctly configured as `pt`.
