### ISSUE TITLE
cannot create directories or files inside var/log

### ISSUE THREAD

**Issue by rgl** [linuxkit/linuxkit#3686]
**Description**

cannot create directories or files inside `var/log`.

**Steps to reproduce the issue:**

none of the following `files` entries work (I also tried to use them separately, and still they do not work).

please note that I can see the files in the final in initrd.img, but for some reason, they do not appear in the booted system.

```yml
kernel:
  image: linuxkit/kernel:5.10.39
  cmdline: "console=tty1"
init:
  - linuxkit/init:78fb57c7da07c4e43c3a37b27755581da087a3b6
  - linuxkit/getty:ed32c71531f5998aa510847bb07bd847492d4101
files:
  - path: var/log/containerd
    directory: true
    mode: "0755"
  - path: var/log/containerd/containerd.log
    contents: ""
    mode: "0644"
```

**Describe the results you received:**

empty `/var/log` directory.

**Describe the results you expected:**

I expected the `/var/log/containerd` and `/var/log/containerd/containerd.log` to appear on the live system.

**Comment by rn** [comment]
How/where do you check? If you use `getty` you are in a namespace. One option to check is to create tarball `linuxkit build -format tar ` and check there.

**Comment by rgl** [comment]
When we run something in the `init` phase, isn't it running in the root namespace?

To give more context, what led me to this problem was containerd failing to start due to the missing `/var/log/containerd` directory when configured as:

```yml
kernel:
  image: linuxkit/kernel:5.10.39
  cmdline: "console=tty1"
init:
  - linuxkit/init:78fb57c7da07c4e43c3a37b27755581da087a3b6
  - linuxkit/runc:bf1e0c61fb4678d6428d0aabbd80db5ea24e4d4d
  - linuxkit/containerd:cc02c2af9c928c2faeccbe4edc78bd297ad91866
files:
  - path: var/log/containerd
    directory: true
    mode: "0755"
  - path: etc/containerd/runtime-config.toml
    contents: |
      cliopts="--log-level debug"
      stderr="/var/log/containerd/containerd.log"
      stdout="/var/log/containerd/containerd.out.log"
    mode: "0644"
```

**Comment by rgl** [comment]
Now that I've disabled `getty`, I can show you the error at the machine console; in this example (different that previous), is showing a failure to launch the docker service because the `/var/lib/docker` directory does not exist:

![image](https://user-images.githubusercontent.com/43356/120936437-a7da6500-c6ff-11eb-9893-6b18a85cafa2.png)

But that directory was declared in the `files` section:

```yml
services:
  - name: docker
    image: local/docker:20.10.7-dind
    capabilities: [all]
    net: host
    mounts:
      - type: cgroup
        options: ["rw", "nosuid", "nodev", "noexec", "relatime"]
    binds:
      - /etc/resolv.conf:/etc/resolv.conf
      - /var/lib/docker:/var/lib/docker
      - /lib/modules:/lib/modules
      - /etc/docker/daemon.json:/etc/docker/daemon.json
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
files:
  - path: var/lib/docker
    directory: true
    mode: "0755"
```
