### ISSUE TITLE
acpid: operation not permitted

### ISSUE THREAD

**Issue by sprat** [linuxkit/linuxkit#3738]
**Description**

I am pretty sure that ACPID does not work properly, my machine does not stop when I hit the power button and I've seen a problem in the ACPID logs:
```
(ns: sshd) linuxkit-b8aeed7efdbc:/# cat /var/log/acpid.log
acpid: /dev/input/event0: Operation not permitted
```
I suspect that it is due to the runc version update that was performed recently: acpid probably need to be allowed to access some devices in order to work. However, I have no idea how to fix that: which devices need to be enabled?

**Steps to reproduce the issue:**

Here is a part of my configuration:
```
kernel:
  image: linuxkit/kernel:5.10.76
  cmdline: console=tty0
  ucode: intel-ucode.cpio
init:
  - linuxkit/init:eb597ef74d808b5320ad1060b1620a6ac31e7ced
  - linuxkit/runc:21dbbda709ae138de0af6b0c7e4ae49525db5e88
  - linuxkit/containerd:2f0907913dd54ab5186006034eb224a0da12443e
services:
  - name: acpid
    image: linuxkit/acpid:e9a94e593d6be2fc1b3eb6d566f23ac9ca9807fd
```

**Describe the results you received:**

There's an error in /var/log/acpid.log

**Describe the results you expected:**

My machine should stop when I hit the power button.

**Additional information you deem important (e.g. issue happens only occasionally):**

None
