### ISSUE TITLE
RPi build fails

### ISSUE THREAD

**Issue by ulm0** [linuxkit/linuxkit#3754]
**Description**

I'm currently unable to build linuxkit for rpi

**Steps to reproduce the issue:**

`linuxkit -v ibuild -format rpi3 rpi3.yml`

<details>
<summary>Yaml content</summary>
<br>

```yaml
kernel:
  image: linuxkit/kernel:5.6.11
  cmdline: "console=serial0,115200 console=tty1 root=/dev/ram0 rw"
  ucode: ""
init:
  - linuxkit/init:e93b0bf37b030238d33e04b98e90d087637f3d2c
  - linuxkit/runc:v0.8
  - linuxkit/containerd:v0.8
  - linuxkit/ca-certificates:v0.8
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.8
  # - name: rngd1
    # image: linuxkit/rngd:v0.8
    # command: ["/sbin/rngd", "-1"]
  # HW RNG for RPi4
  # - name: hwrng
    # image: linuxkit/modprobe:v0.8
    # command: ["modprobe", "iproc-rng200" ]
  # Net for RPi4
  # - name: netdev
    # image: linuxkit/modprobe:v0.8
    # command: ["modprobe", "mdio-bcm-unimac" ]
  - name: netdev
    image: linuxkit/modprobe:v0.8
    command: ["modprobe", "lan78xx" ]
  # SD Card for RPi 
  # - name: block
    # image: linuxkit/modprobe:v0.8
    # command: ["modprobe", "mmc_block" ]
  # - name: sdhci
    # image: linuxkit/modprobe:v0.8
    # command: ["modprobe", "sdhci-iproc" ] # RPi4
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.8
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: linuxkit/getty:v0.8
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:v0.8
    command: ["rngd", "-f", "-r", "/dev/hwrng"]
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.8
trust:
  org:
    - linuxkit
    - library
```
</details>

**Describe the results you received:**

`Error writing outputs: Raspberry Pi output currently only supported on arm64`

<details>
<summary>Logs</summary>
<br>

```sh
ttime="2022-01-12T00:57:01-03:00" level=info msg="Create outputs:"
time="2022-01-12T00:57:01-03:00" level=debug msg="format: [rpi3] rpi3"
time="2022-01-12T00:57:01-03:00" level=debug msg="validating output: [rpi3]"
time="2022-01-12T00:57:01-03:00" level=fatal msg="Error writing outputs: Raspberry Pi output currently only supported on arm64"
```
</details>

**Describe the results you expected:**

An image for rpi3

**Additional information**

Github won't let me paste the whole log so i uploaded it in a file

[output.log](https://github.com/linuxkit/linuxkit/files/7851578/output.log)
