### ISSUE TITLE
Not able to use locally built docker images with `linuxkit build linuxkit.yml` command

### ISSUE THREAD

**Issue by MohammadAli-Khodabandelou** [linuxkit/linuxkit#3944]
Hi there
I compiled the latest version of the stable kernel which is 6.4.6 using LLVM. Then I used the `bzImage` to build a docker image using the Dockerfile below
```
FROM linuxkit/kernel:5.4.116 AS ksrc
FROM alpine
RUN apk add build-base

ENTRYPOINT []
CMD []
WORKDIR /

COPY --from=ksrc /kernel-dev.tar /
COPY --from=ksrc /kernel.tar /
COPY bzImage /kernel
# docker build . -t gcov-kernel --no-cache
```

Now, I want to use this image in a `linuxkit.yml` file but when I run the command `linuxkit build linuxkit.yml`, It tries to pull the image from DockerHub.
This is my `linuxkit.yml` file contents:
```
kernel:
    image: gcov-kernel:latest
    cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:v0.8
  - linuxkit/runc:v0.8
  - linuxkit/containerd:v0.8
  - linuxkit/ca-certificates:v0.8
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.8
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.8
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
onshutdown:
  - name: shutdown
    image: busybox:latest
    command: ["/bin/echo", "so long and thanks for all the fish"]
services:
  - name: getty
    image: linuxkit/getty:v0.8
    env:
     - INSECURE=true
  - name: ubuntu
    image: ubuntu:20.04
    binds:
        - /etc/resolv.conf:/etc/resolv.conf
        - /id_rsa:/home/id_rsa
    capabilities:
        - ALL
    command: ["/bin/sh", "-c", "/bin/sleep infinity"]
files:
  - path: id_rsa
    source: "/home/prasant/.ssh/id_rsa"
    mode: "0600"
  - path: collect.sh
    source: "/home/prasant/workspace/linuxkit/collect.sh"
    mode: "0755"
trust:
  org:
    - linuxkit
    - library
```

This the output of `docker images` command on my machine:
```
REPOSITORY            TAG                                        IMAGE ID       CREATED        SIZE
gcov-kernel           latest                                     f361accdff21   22 hours ago   433MB
linuxkit/kconfig      latest                                     311992b55884   23 hours ago   4.42GB
alpine                latest                                     c1aabb73d233   6 weeks ago    7.33MB
linuxkit/go-compile   c97703655e8510b7257ffc57f25e40337b0f0813   4f3f7edff228   6 months ago   613MB
linuxkit/kernel       5.4.116                                    cf237b55b2b2   2 years ago    306MB
linuxkit/alpine       2be490394653b7967c250e86fd42cef88de428ba   136934fa2354   2 years ago    795MB
```

Finally, this is the output when I run the `linuxkit build linuxkit.yml` command:
```
Extract kernel image: docker.io/linuxkit/gcov-kernel:latest
Image docker.io/linuxkit/gcov-kernel:latest arch amd64 not found in local cache, pulling
Error: Failed to extract kernel image and tarball: Could not pull image docker.io/linuxkit/gcov-kernel:latest: error gett]
2023/07/30 12:40:28 error during command execution: Failed to extract kernel image and tarball: Could not pull image dock]
```
