### ISSUE TITLE
Kernel 6.6.71 - Not Working/ No Output using Go vz Framework

### ISSUE THREAD

**Issue by bdwyertech** [linuxkit/linuxkit#4119]
I'm using `github.com/Code-Hex/vz/v3`.  Updating my config.yml from 6.6.13 to 6.6.71 results in no output under this framework.  Not sure whats changed between the two.  The cmdline under this framework uses hvc0 as the console device.  Code is basically the same as listed here: https://github.com/Code-Hex/vz/blob/main/example/linux/main.go

```yaml
kernel:
  # image: linuxkit/kernel:6.6.13
  image: linuxkit/kernel:6.6.71
  cmdline: 'console=ttyS0 disable_ipv6=true'
init:
  - linuxkit/init:8eea386739975a43af558eec757a7dcb3a3d2e7b
  - linuxkit/runc:667e7ea2c426a2460ca21e3da065a57dbb3369c9
  - linuxkit/containerd:a988a1a8bcbacc2c0390ca0c08f949e2b4b5915d
  - linuxkit/ca-certificates:7b32a26ca9c275d3ef32b11fe2a83dbd2aee2fdb
onboot:
  - name: sysctl
    image: linuxkit/sysctl:5f56434b81004b50b47ed629b222619168c2bcdf
  - name: dhcpcd
    image: linuxkit/dhcpcd:330839488cd122db3c44738e265c035c9729a963
    command: ['/sbin/dhcpcd', '--nobackground', '-f', '/dhcpcd.conf', '-1']
services:
  - name: getty
    image: linuxkit/getty:05eca453695984a69617f1f1f0bcdae7f7032967
    env:
      - INSECURE=true
```
