### ISSUE TITLE
Service not restarted

### ISSUE THREAD

**Issue by webfrank** [linuxkit/linuxkit#4121]
Hi, I have a go application, configured as a service, which sometimes crashes (investigating) but the service is never restarted and I need to reset the VM.

The only difference is logging to console:

```yaml
- name: landscape
    image: ***redacted***
    capabilities:
     - CAP_NET_BIND_SERVICE
    binds.add:
    - /etc/resolv.conf:/etc/resolv.conf
    - /var/lib/landscape:/app/data
    command: ["sh", "-c", "/app/landscape > /dev/console 2>&1"]
    net: host
    devices:
    - path: "/dev/console"
      type: c
      major: 5
      minor: 1
      mode: "0666"
```

**Comment by deitch** [comment]
> never restarted

True. This probably could be supported with [containerd's restart extension](https://pkg.go.dev/github.com/containerd/containerd/runtime/restart). Although I have not used it.

Would be more than happy to accept a PR with it.

**Comment by Smithx10** [comment]
I was just wondering about this problem when I was testing out linux kit.   I killed a process in the containerd container to see what would happen.  And then I attempted to get it backup and running.    I guess this just needs to be plumbed into the config and do the correct thing.      How did folks solve this problem prior, an init system inside the container?

**Comment by deitch** [comment]
> I guess this just needs to be plumbed into the config and do the correct thing

Pretty much. There is nothing inherent in the structure that says we cannot do it. Arguably, it probably is the right thing to do in all cases, so not even sure it needs to be plumbed into config, except someone might say, "oh no, I do not want restart", so maybe it becomes the default and has an option to disable it?

> How did folks solve this problem prior, an init system inside the container?

Mostly. If we can get this to work, all the better. It uses containerd 2.0 anyways since a few months ago, so quite up to date.

**Comment by Smithx10** [comment]
@deitch,

From my understanding unless things have changed, it would be on us to implement the restart logic in:

/var/tmp/linuxkit/pkg/init/cmd/service

Does linuxkit at the moment have any process that is long running currently or does it exit?    Where would you like the task/container restart logic to live?

https://github.com/containerd/containerd/issues/905#event-1097609674

**Comment by deitch** [comment]
I would do the following, I think:

* Change containerd config to enable the restart plugin. It is in `pkg/containerd/etc/containerd/config.toml]. If I recall correctly, it is something like:
```toml
[plugins."io.containerd.service.v1.restart"]
  interval = "10s"  # How often to check container state for restarts
```
* add to docs that containers can be set to restart via labels
* add a test that uses another service to kill the first, so we can see that it works

I am pretty sure that the labels to be used are:

* ` io.containerd.runtime.v2.task.restart.policy` - one of: `always`, `on-failure` (optional max-retries), `no`, `unless-stopped` (default `no`)
* `io.containerd.runtime.v2.task.restart.delay` - time, e.g. `5s`

It is listed [here](https://pkg.go.dev/github.com/containerd/containerd/runtime/restart#NewPolicy)

Then set the label either on the container image or in the actual `linuxkit.yaml`.
